; Saffron City -- while Silph Co is occupied -- the plain songs.asm entry.
;
; GENERATED by .claude/port_gen2_music.py from pokecrystal's Goldenrod City.
; Do not edit this file; edit that one and re-run it.
;
; Forte's call, after three original melodies for Saffron were all rejected as
; "bootleg": take Goldenrod, Gen 2's big-city theme, and run it faster. That is
; what this is. The tune is Game Freak's, so it cannot sound like an imitation
; of Game Freak -- everything decided here is arrangement and tempo.
;
; TEMPO 156, against Goldenrod's 176. Bigger is slower in both engines (the
; delay is NoteLength * delay_units * Tempo either side), so this is about 13%
; quicker. Gen 2's Bicycle sits at 140 and was the stated ceiling. 156 is also
; Vermilion's exact tempo, so it is a value this game already uses.
;   Note for the record: the Bicycle theme is NOT Goldenrod sped up, whatever it
;   sounds like -- their Ch1 note data differs. Relatives, not the same piece.
;
; The port is pitch-exact and needs no transposition: audio/notes.asm here and
; in pokecrystal hold byte-identical frequency tables.
;
; THREE CHANNELS: Goldenrod without its drum track. The kit
; arriving is what beating Giovanni sounds like -- see
; saffronfree.asm, which is this same port with Ch4 kept.
;
; Two things were changed rather than copied, both because Gen 1 would silently
; get them wrong:
;   - Goldenrod's Ch4 uses two `sound_loop 3` blocks. Gen 1's sound_loop plays
;     its block N+1 times on the first pass and N after, so that channel would
;     drift permanently out of phase. Both are unrolled here.
;   - Its drums are Gen 2 drumkit 3, which does not exist here. Mapped on the
;     noise data: Snare13 -> 4, Snare14 -> 3, Drum20 -> 8, Drum27 -> 12.
;   - stereo_panning is dropped; Gen 1 stores it in one global rather than per
;     channel, and no map theme in this game uses it.
;
; Check with: python .claude/music_analyze.py saffroncity

Music_SaffronCity_Ch1::
	tempo 200
	volume 7, 7
	note_type 12, 6, 7
	rest 16
	rest 16
	rest 16
	rest 16
.mainloop:
	duty_cycle 0
	sound_call .sub1
	octave 3
	note G#, 1
	octave 4
	note C_, 1
	note D#, 1
	note F#, 1
	note D#, 1
	note F#, 1
	note G#, 1
	octave 5
	note C_, 1
	note_type 12, 4, 1
	duty_cycle 0
	sound_call .sub2
	note_type 12, 4, 7
	note D#, 2
	note F_, 2
	note F#, 2
	note G#, 4
	note_type 12, 4, 1
	sound_call .sub2
	note D#, 1
	note F#, 1
	note_type 12, 4, 7
	octave 5
	note C_, 2
	octave 4
	note G#, 2
	note F#, 2
	note D#, 2
	duty_cycle 2
	note_type 12, 6, 7
	sound_call .sub1
	note C_, 4
	octave 3
	note G#, 2
	octave 4
	note C_, 2
	sound_loop 0, .mainloop
.sub1:
	octave 4
	note C#, 2
	octave 3
	note G#, 1
	rest 3
	note G#, 1
	rest 1
	octave 4
	note C_, 2
	octave 3
	note G#, 1
	rest 3
	note G#, 1
	rest 1
	note A#, 2
	note F_, 1
	rest 1
	note C#, 2
	note F_, 1
	rest 1
	note D#, 2
	note C_, 2
	note C#, 2
	note D#, 2
	note F#, 2
	note C#, 1
	rest 3
	note C#, 1
	rest 1
	note F#, 2
	note C#, 1
	rest 1
	note F#, 2
	note A#, 2
	note C#, 2
	note D#, 2
	note G#, 2
	octave 4
	note C#, 2
	sound_ret
.sub2:
	octave 4
	note F_, 1
	note C#, 1
	octave 3
	note G#, 1
	octave 4
	note C#, 1
	note F_, 1
	note G#, 1
	note F_, 1
	note G#, 1
	note C#, 1
	octave 3
	note G#, 1
	note F_, 1
	note G#, 1
	octave 4
	note C#, 1
	note F_, 1
	note C#, 1
	note F_, 1
	note D#, 1
	note C_, 1
	octave 3
	note G#, 1
	octave 4
	note C_, 1
	note D#, 1
	note F#, 1
	note D#, 1
	note F#, 1
	note C_, 1
	octave 3
	note G#, 1
	note F#, 1
	note G#, 1
	octave 4
	note C_, 1
	note D#, 1
	note C_, 1
	note D#, 1
	note C#, 1
	octave 3
	note A#, 1
	note F#, 1
	note A#, 1
	octave 4
	note C#, 1
	note F_, 1
	note C#, 1
	note F_, 1
	octave 3
	note A#, 1
	note F#, 1
	note C#, 1
	note F#, 1
	note A#, 1
	octave 4
	note C#, 1
	octave 3
	note A#, 1
	octave 4
	note C#, 1
	note D#, 1
	note C_, 1
	octave 3
	note G#, 1
	octave 4
	note C_, 1
	note D#, 1
	note F#, 1
	sound_ret

Music_SaffronCity_Ch2::
	vibrato 18, 2, 3
	duty_cycle 2
	note_type 12, 6, 7
.mainloop:
	note_type 12, 6, 7
	sound_call .sub1
	octave 4
	note F_, 2
	note F#, 2
	note G#, 2
	note F_, 2
	note D#, 8
	sound_call .sub1
	note G#, 2
	note A#, 2
	octave 5
	note C_, 2
	note C#, 2
	note D#, 8
	duty_cycle 2
	note_type 12, 4, 7
	sound_call .sub2
	octave 4
	note G#, 2
	note A#, 2
	note B_, 2
	octave 5
	note C_, 4
	duty_cycle 3
	note_type 12, 4, 7
	sound_call .sub2
	note F_, 2
	note D#, 2
	note C#, 2
	note C_, 2
	octave 4
	note G#, 2
	sound_loop 0, .mainloop
.sub1:
	octave 4
	note F_, 4
	note C#, 4
	note D#, 4
	note C_, 4
	note C#, 2
	note C_, 2
	octave 3
	note A#, 2
	octave 4
	note C_, 2
	octave 3
	note G#, 6
	octave 3
	note G#, 1
	octave 3
	note A_, 1
	note A#, 4
	octave 4
	note C#, 4
	octave 3
	note A#, 2
	octave 4
	note A#, 2
	note G#, 2
	note F#, 2
	duty_cycle 1
	sound_ret
.sub2:
	note C#, 6
	note F_, 6
	note C#, 4
	note C_, 6
	note D#, 6
	note C_, 2
	octave 4
	note G#, 1
	note A_, 1
	note A#, 6
	octave 5
	note C#, 6
	octave 4
	note A#, 4
	octave 5
	note C_, 4
	note D#, 2
	sound_ret

Music_SaffronCity_Ch3::
	vibrato 8, 2, 3
; wave 5 has no data in this engine -- 1 is the one the town themes use
	note_type 12, 2, 1
.mainloop:
	sound_call .sub1
	sound_call .sub1
	sound_call .sub2
	rest 3
	octave 3
	note C_, 1
	note D#, 1
	note G_, 1
	note G#, 1
	note D#, 2
	sound_call .sub2
	rest 1
	octave 3
	note G#, 2
	note F#, 2
	note D#, 2
	octave 2
	note G#, 2
	sound_loop 0, .mainloop
.sub1:
	octave 3
	note C#, 4
	rest 2
	note C#, 1
	rest 1
	note C_, 4
	rest 2
	note C_, 1
	rest 1
	octave 2
	note A#, 4
	rest 2
	note A#, 1
	rest 1
	note G#, 4
	rest 2
	note G#, 1
	rest 1
	note F#, 4
	rest 2
	note F#, 1
	rest 1
	octave 3
	note D#, 4
	rest 2
	note D#, 1
	rest 1
	note G#, 4
	rest 2
	note G#, 1
	rest 1
	octave 2
	note G#, 1
	rest 1
	note G#, 3
	rest 1
	octave 3
	note G#, 1
	rest 1
	sound_ret
.sub2:
	note C#, 1
	rest 1
	octave 4
	note C#, 1
	octave 3
	note C#, 1
	rest 2
	note C#, 1
	rest 5
	octave 4
	note C_, 1
	note C#, 1
	octave 3
	note G#, 2
	note C_, 1
	rest 1
	octave 4
	note C_, 1
	octave 3
	note C_, 1
	rest 2
	note C_, 1
	rest 5
	note B_, 1
	octave 4
	note C_, 1
	octave 3
	note G#, 2
	octave 2
	note A#, 1
	rest 1
	octave 3
	note A#, 1
	octave 2
	note A#, 1
	rest 2
	note A#, 1
	rest 5
	octave 3
	note A_, 1
	note A#, 1
	note F#, 2
	octave 2
	note G#, 1
	rest 1
	octave 3
	note G#, 1
	octave 2
	note G#, 1
	rest 2
	note G#, 1
	sound_ret
