#!/usr/bin/env python3
"""
Purple Yellow - ROM Bank Memory Usage Analyzer
Parses pokeyellow.map (generated by rgblink -m) and shows bank occupancy.

Usage:
    python3 bank_usage.py pokeyellow.map
    python3 bank_usage.py pokeyellow.map --top 10
"""

import re
import sys

BANK_SIZE = 16384  # 16 KB per bank


def parse_map_file(filepath):
    with open(filepath, "r") as f:
        content = f.read()

    banks = []

    # ROM0
    rom0_match = re.search(
        r"ROM0 bank #0:\n(.*?)(?=ROMX bank|SUMMARY)", content, re.DOTALL
    )
    if rom0_match:
        total = re.findall(
            r"TOTAL EMPTY: \$([0-9a-fA-F]+) bytes", rom0_match.group(1)
        )
        empty = int(total[0], 16) if total else 0
        banks.append({"name": "ROM0", "num": 0, "empty": empty})

    # ROMX banks
    for m in re.finditer(
        r"ROMX bank #(\d+):\n(.*?)(?=ROMX bank|SRAM|WRAM|HRAM|SUMMARY)",
        content,
        re.DOTALL,
    ):
        num = int(m.group(1))
        total = re.findall(
            r"TOTAL EMPTY: \$([0-9a-fA-F]+) bytes", m.group(2)
        )
        empty = int(total[0], 16) if total else 0
        banks.append({"name": f"Bank {num}", "num": num, "empty": empty})

    banks.sort(key=lambda x: x["num"])
    return banks


def print_report(banks, top_n=None):
    total_free = sum(b["empty"] for b in banks)
    total_capacity = len(banks) * BANK_SIZE
    full_banks = [b for b in banks if b["empty"] == 0]

    # Header
    print("=" * 66)
    print("  PURPLE YELLOW - ROM BANK MEMORY MAP")
    print("=" * 66)
    print(
        f"  Total: {total_free:,}B livre ({total_free/1024:.1f} KB) "
        f"de {total_capacity/1024:.0f} KB  |  "
        f"{len(full_banks)} banks cheios  |  "
        f"{len([b for b in banks if b['empty'] >= 1024])} banks com 1KB+ livre"
    )
    print("=" * 66)
    print()

    # Bar chart
    print(f"{'Bank':<10} {'Usado':>6} {'Livre':>6} {'%Livre':>6}  {'Ocupação'}")
    print("-" * 66)

    for b in banks:
        used = BANK_SIZE - b["empty"]
        pct_used = (used / BANK_SIZE) * 100
        pct_free = (b["empty"] / BANK_SIZE) * 100
        bar_len = 25
        filled = int(pct_used / (100 / bar_len))
        bar = "█" * filled + "░" * (bar_len - filled)

        label = "ROM0" if b["num"] == 0 else f"Bank {b['num']:>2}"

        # Color hint
        if b["empty"] == 0:
            marker = " FULL"
        elif pct_free >= 30:
            marker = " <<<" 
        elif pct_free >= 10:
            marker = ""
        else:
            marker = ""

        print(
            f"{label:<10} {used:>5}B {b['empty']:>5}B {pct_free:>5.1f}%  "
            f"[{bar}]{marker}"
        )

    print("-" * 66)

    # Top free banks
    big_free = sorted(
        [b for b in banks if b["empty"] >= 1024],
        key=lambda x: -x["empty"],
    )
    if top_n:
        big_free = big_free[:top_n]

    print(f"\nBanks com mais espaço livre ({len(big_free)}):")
    for b in big_free:
        pct = b["empty"] / BANK_SIZE * 100
        print(
            f"  {b['name']:<10} {b['empty']:>5}B  "
            f"({b['empty']/1024:.1f} KB)  {pct:.0f}% livre"
        )

    # Full banks
    print(
        f"\nCompletamente cheios ({len(full_banks)}): "
        + ", ".join(b["name"] for b in full_banks)
    )
    print()


def main():
    if len(sys.argv) < 2:
        print("Uso: python3 bank_usage.py pokeyellow.map [--top N]")
        sys.exit(1)

    filepath = sys.argv[1]
    top_n = None
    if "--top" in sys.argv:
        idx = sys.argv.index("--top")
        if idx + 1 < len(sys.argv):
            top_n = int(sys.argv[idx + 1])

    banks = parse_map_file(filepath)
    print_report(banks, top_n)


if __name__ == "__main__":
    main()
