Music_SurfingPikachu::
	channel_count 3
	channel 1, Music_SurfingPikachu_Ch1
	channel 2, Music_SurfingPikachu_Ch2
	channel 3, Music_SurfingPikachu_Ch3

Music_MeetJessieJames::
	channel_count 3
	channel 1, Music_MeetJessieJames_Ch1
	channel 2, Music_MeetJessieJames_Ch2
	channel 3, Music_MeetJessieJames_Ch3

Music_YellowUnusedSong::
	channel_count 4
	channel 1, Music_YellowUnusedSong_Ch1
	channel 2, Music_YellowUnusedSong_Ch2
	channel 3, Music_YellowUnusedSong_Ch3
	channel 4, Music_YellowUnusedSong_Ch4

; Cinnabar Island, Cinnabar Lab.
;
; It lives in AUDIO_4 and not beside the other town themes for a hard reason:
; song ids are (header - $4000) / 3 within the bank, AUDIO_1's table already
; ends at id 251, and a 4-channel header needs four consecutive ids. 252-254
; is three. Placed there it landed on 255 -- which is SFX_STOP_ALL_MUSIC, so
; the island silenced itself instead of playing. The build cannot see that:
; it was caught by recording the track and getting 22 seconds of nothing.
Music_CinnabarIsland::
	channel_count 4
	channel 1, Music_CinnabarIsland_Ch1
	channel 2, Music_CinnabarIsland_Ch2
	channel 3, Music_CinnabarIsland_Ch3
	channel 4, Music_CinnabarIsland_Ch4

; Pewter City. AUDIO_4 for the same reason as Cinnabar Island above: AUDIO_1's
; id space ends at 251 and a header needs one id per channel.
Music_PewterCity::
	channel_count 4
	channel 1, Music_PewterCity_Ch1
	channel 2, Music_PewterCity_Ch2
	channel 3, Music_PewterCity_Ch3
	channel 4, Music_PewterCity_Ch4

; Saffron City while Silph Co is still occupied -- the plain table entry.
;
; THREE channels, and the missing one is the point: there is no percussion in
; the occupied city. Beating Giovanni is what brings the drums in, so
; Music_SaffronFree below has four. Drumless is not unusual -- Cities2, Celadon
; and Pallet are all three-channel.
Music_SaffronCity::
	channel_count 3
	channel 1, Music_SaffronCity_Ch1
	channel 2, Music_SaffronCity_Ch2
	channel 3, Music_SaffronCity_Ch3

; The same melody, the same key and the same tempo, once Giovanni is beaten --
; what changes is the accompaniment. Reached through LoadMapMusicOverrides,
; never from the song table. Both files are generated by .claude/saffron_build.py.
Music_SaffronFree::
	channel_count 4
	channel 1, Music_SaffronFree_Ch1
	channel 2, Music_SaffronFree_Ch2
	channel 3, Music_SaffronFree_Ch3
	channel 4, Music_SaffronFree_Ch4

; Cerulean City, which used to share Cities2 with Fuchsia. AUDIO_4 for the same
; reason as the two above.
;
; This header is LAST on purpose, and anything added later has to go after it.
; Song ids are (header - $4000) / 3 within the bank, so inserting a header
; renumbers every song below it -- including ids that are already baked into
; data/maps/songs.asm and into save files. Appending costs nothing.
Music_CeruleanCity::
	channel_count 4
	channel 1, Music_CeruleanCity_Ch1
	channel 2, Music_CeruleanCity_Ch2
	channel 3, Music_CeruleanCity_Ch3
	channel 4, Music_CeruleanCity_Ch4


