; AUDIO_5: the five city themes.
;
; This bank exists so that the cities can have BOTH their own music and a full
; SFX+cry mirror (sfxheaders5.asm). They used to live in AUDIO_4, whose vanilla
; SFX table is the short one -- any overworld sound there resolved to garbage
; and wedged channels 5-8, which is what killed the music on the Pewter ledge
; (bug #7 of Forte's first playthrough).
;
; Song ids are (header - $4000) / 3 within the bank. These headers sit directly
; after the sfx mirror, so their ids start where MAX_SFX_ID_5 ends. Same rule
; as everywhere: NEVER insert a header mid-table -- ids of everything below
; would shift. Append only.

Music_CinnabarIsland::
	channel_count 4
	channel 1, Music_CinnabarIsland_Ch1
	channel 2, Music_CinnabarIsland_Ch2
	channel 3, Music_CinnabarIsland_Ch3
	channel 4, Music_CinnabarIsland_Ch4

Music_PewterCity::
	channel_count 4
	channel 1, Music_PewterCity_Ch1
	channel 2, Music_PewterCity_Ch2
	channel 3, Music_PewterCity_Ch3
	channel 4, Music_PewterCity_Ch4

; Saffron City while Silph Co is still occupied -- the plain table entry.
;
; THREE channels, and the missing one is the point: there is no percussion in
; the occupied city. Beating Giovanni is what brings the drums in, so
; Music_SaffronFree below has four. Drumless is not unusual -- Cities2, Celadon
; and Pallet are all three-channel.
Music_SaffronCity::
	channel_count 3
	channel 1, Music_SaffronCity_Ch1
	channel 2, Music_SaffronCity_Ch2
	channel 3, Music_SaffronCity_Ch3

; The same melody, the same key and the same tempo, once Giovanni is beaten --
; what changes is the accompaniment. Reached through LoadMapMusicOverrides,
; never from the song table. Both files are generated by .claude/saffron_build.py.
Music_SaffronFree::
	channel_count 4
	channel 1, Music_SaffronFree_Ch1
	channel 2, Music_SaffronFree_Ch2
	channel 3, Music_SaffronFree_Ch3
	channel 4, Music_SaffronFree_Ch4

Music_CeruleanCity::
	channel_count 4
	channel 1, Music_CeruleanCity_Ch1
	channel 2, Music_CeruleanCity_Ch2
	channel 3, Music_CeruleanCity_Ch3
	channel 4, Music_CeruleanCity_Ch4

; The Fighting Dojo's permanent theme (and the Viridian semi-boss speech).
; Moved from AUDIO_4 for the same reason as the cities: the Dojo is a walkable
; map, and a Pokedex cry, a save or a poison step under the short bank-$20
; table wedged channels 5-8. Appended last, as the rule above demands.
Music_YellowUnusedSong::
	channel_count 4
	channel 1, Music_YellowUnusedSong_Ch1
	channel 2, Music_YellowUnusedSong_Ch2
	channel 3, Music_YellowUnusedSong_Ch3
	channel 4, Music_YellowUnusedSong_Ch4
