; v0.7: MOVE INFO flavour, one entry per move.
;
; Printed above the shared mechanics block. Unlike the mechanics -- keyed to the
; effect on purpose, so two moves that behave alike read alike -- every one of
; these is written for its own move.
;
; Two rules shaped them. The move's NAME has to land: GORE ATTACK reads as
; bloody because that is what it is called. And the ANATOMY has to fit EVERY
; Pokemon that learns it -- TACKLE cannot be "a shoulder charge" when MAGIKARP
; knows it, and NUZZLE cannot mention cheeks when TENTACOOL does.
;
; Generated by .claude/flavor_build.py from prose; do not hand-edit the line
; breaks here, edit the prose and re-run.

; Part 5 of 5.

_MoveFlavor_DEFENSE_CURL::
	text "The user tucks"
	next "everything soft"
	next "away behind"
	next "everything hard."
	done

_MoveFlavor_HARDEN::
	text "The user stiffens"
	next "all over and waits"
	next "to be hit."
	done

_MoveFlavor_WITHDRAW::
	text "The user pulls in"
	next "behind its shell"
	next "and lets the blow"
	next "come."
	done

_MoveFlavor_GROWTH::
	text "The user swells"
	next "with a rush of"
	next "vigour, healthier"
	next "and stronger in"
	next "mind."
	done

_MoveFlavor_CALM_MIND::
	text "The user goes"
	next "quiet inside, and"
	next "thinks more"
	next "clearly for it."
	done

_MoveFlavor_NASTY_PLOT::
	text "The user dwells on"
	next "something spiteful"
	next "until the idea"
	next "itself gives it an"
	next "edge."
	done

_MoveFlavor_AMNESIA::
	text "The user lets"
	next "everything go, and"
	next "finds its mind"
	next "clearer for it."
	done

_MoveFlavor_QUIVER_DANCE::
	text "A trembling,"
	next "careful dance that"
	next "leaves the user"
	next "sharper all round."
	done

_MoveFlavor_TAILWIND::
	text "The air is set"
	next "moving the user's"
	next "way and stays that"
	next "way."
	done

_MoveFlavor_AGILITY::
	text "The user loosens"
	next "up until nothing"
	next "about it is slow"
	next "any more."
	done

_MoveFlavor_DOUBLE_TEAM::
	text "The user moves so"
	next "that there seem to"
	next "be more of it than"
	next "there are."
	done

_MoveFlavor_TELEPORT::
	text "The user is"
	next "elsewhere, and"
	next "there was no"
	next "moment of leaving."
	done

_MoveFlavor_CHARM::
	text "The user makes"
	next "friends of the"
	next "foe, which then"
	next "cannot bring"
	next "itself to hit"
	next "hard."
	done

_MoveFlavor_INTIMIDATE::
	text "One look, held a"
	next "moment too long."
	next "The foe's nerve"
	next "goes with it."
	done

_MoveFlavor_GROWL::
	text "A sound pitched to"
	next "take the fight out"
	next "of the foe. A"
	next "warning from some,"
	next "a plea from"
	next "others."
	done

_MoveFlavor_LEER::
	text "A flat, unblinking"
	next "stare that finds"
	next "the gaps in the"
	next "guard."
	done

_MoveFlavor_CORRODE::
	text "An acid spray that"
	next "eats its way"
	next "through the foe's"
	next "guard."
	done

_MoveFlavor_TICKLE::
	text "The foe is made to"
	next "laugh, and nothing"
	next "holds together"
	next "while it does."
	done

_MoveFlavor_TAIL_WHIP::
	text "The tail sweeps"
	next "back and forth."
	next "Eyes follow it,"
	next "and the guard"
	next "drops."
	done

_MoveFlavor_FAKE_TEARS::
	text "The user weeps,"
	next "and the foe"
	next "believes it. Pity"
	next "is a poor state to"
	next "fight in."
	done

_MoveFlavor_METAL_SOUND::
	text "A scraping note"
	next "that sets the"
	next "teeth on edge and"
	next "the nerves after."
	done

_MoveFlavor_SCREECH::
	text "A shriek at a"
	next "pitch that breaks"
	next "the foe's focus."
	done

_MoveFlavor_EERIE_IMPULSE::
	text "A pulse that"
	next "leaves the foe's"
	next "edge blunted and"
	next "its aim off."
	done

_MoveFlavor_SCARY_FACE::
	text "The user pulls a"
	next "face so frightful"
	next "the foe forgets"
	next "how to move"
	next "quickly."
	done

_MoveFlavor_HINDER::
	text "The user gets in"
	next "the way and stays"
	next "there, and nothing"
	next "runs smoothly."
	done

_MoveFlavor_STRING_SHOT::
	text "Thread laid over"
	next "the foe's legs"
	next "until moving is"
	next "more trouble."
	done

_MoveFlavor_PSYCHIC_BIND::
	text "The user takes"
	next "hold of the foe's"
	next "mind and simply"
	next "holds it still."
	done

_MoveFlavor_FLASH::
	text "A blast of white"
	next "light straight"
	next "into the foe's"
	next "eyes."
	done

_MoveFlavor_SAND_ATTACK::
	text "A handful of grit"
	next "thrown at the"
	next "face. Cheap, and"
	next "it works."
	done

_MoveFlavor_SMOKESCREEN::
	text "A gout of smoke"
	next "put up between the"
	next "two of them."
	done

_MoveFlavor_RECOVER::
	text "The user goes"
	next "still and lets its"
	next "body put itself"
	next "back together."
	done

_MoveFlavor_REST::
	text "The user lies down"
	next "and refuses to get"
	next "up until it is"
	next "whole."
	done

_MoveFlavor_SOFTBOILED::
	text "The user takes the"
	next "egg it carries and"
	next "makes a meal of"
	next "it."
	done

_MoveFlavor_LIGHT_SCREEN::
	text "A thin, bright"
	next "wall that blunts"
	next "what comes at the"
	next "mind."
	done

_MoveFlavor_REFLECT::
	text "A thin, bright"
	next "wall that blunts"
	next "what comes at the"
	next "body."
	done

_MoveFlavor_BIDE::
	text "The user stands"
	next "and takes it, then"
	next "hands all of it"
	next "back."
	done

_MoveFlavor_FOCUS_ENERGY::
	text "The user gathers"
	next "itself and starts"
	next "looking for the"
	next "weak spot."
	done

_MoveFlavor_MIMIC::
	text "The user watches"
	next "once and can do it"
	next "too."
	done

_MoveFlavor_MIRROR_MOVE::
	text "Whatever the foe"
	next "did last, it is"
	next "about to happen to"
	next "them."
	done

_MoveFlavor_SUBSTITUTE::
	text "The user spends"
	next "its own health on"
	next "a double to stand"
	next "in for it."
	done

_MoveFlavor_TRANSFORM::
	text "The user takes on"
	next "the foe's shape,"
	next "and everything"
	next "that goes with it."
	done

_MoveFlavor_METRONOME::
	text "The user waves"
	next "about at random"
	next "and something"
	next "always comes out."
	done

_MoveFlavor_STRUGGLE::
	text "Nothing left to"
	next "use. The user"
	next "throws itself in"
	next "regardless."
	done
