; v0.7: MOVE INFO flavour, one entry per move.
;
; Printed above the shared mechanics block. Unlike the mechanics -- keyed to the
; effect on purpose, so two moves that behave alike read alike -- every one of
; these is written for its own move.
;
; Two rules shaped them. The move's NAME has to land: GORE ATTACK reads as
; bloody because that is what it is called. And the ANATOMY has to fit EVERY
; Pokemon that learns it -- TACKLE cannot be "a shoulder charge" when MAGIKARP
; knows it, and NUZZLE cannot mention cheeks when TENTACOOL does.
;
; Generated by .claude/flavor_build.py from prose; do not hand-edit the line
; breaks here, edit the prose and re-run.

; Part 4 of 5.

_MoveFlavor_POISON_BITE::
	text "A bite that leaves"
	next "more behind it"
	next "than the wound."
	done

_MoveFlavor_TOXIC_FANGS::
	text "A deep bite with a"
	next "heavy dose worked"
	next "into it."
	done

_MoveFlavor_ACID::
	text "A spray that eats"
	next "at whatever it"
	next "settles on."
	done

_MoveFlavor_SLUDGE::
	text "A thrown mass of"
	next "filth, heavy and"
	next "foul enough to"
	next "sting."
	done

_MoveFlavor_SLUDGE_WAVE::
	text "A wave of filth"
	next "washed over the"
	next "whole field."
	done

_MoveFlavor_GUNK_SHOT::
	text "A festering lump"
	next "of filth fired"
	next "point-blank. It"
	next "lands as badly as"
	next "it sounds."
	done

_MoveFlavor_NEUROTOXIN::
	text "A venom that works"
	next "on the nerves, not"
	next "the flesh."
	done

_MoveFlavor_TOXIC::
	text "A dose meant to"
	next "get worse. It is"
	next "patient about it."
	done

_MoveFlavor_PSYWAVE::
	text "A pulse of raw"
	next "thought, and never"
	next "quite the same"
	next "twice."
	done

_MoveFlavor_CONFUSION::
	text "A push against the"
	next "mind. Small, but"
	next "it lands somewhere"
	next "soft."
	done

_MoveFlavor_EXTRASENSORY::
	text "The user reaches"
	next "out with a sense"
	next "the foe does not"
	next "have."
	done

_MoveFlavor_PSYBEAM::
	text "A beam that goes"
	next "through the guard"
	next "and works on what"
	next "is behind it."
	done

_MoveFlavor_PSYCHIC_M::
	text "The full weight of"
	next "the user's mind,"
	next "brought down at"
	next "once."
	done

_MoveFlavor_MIND_BREAK::
	text "The user seizes"
	next "the foe's mind and"
	next "crushes, and the"
	next "body locks up with"
	next "it."
	done

_MoveFlavor_DISABLE::
	text "The user fixes on"
	next "one move and"
	next "quietly takes it"
	next "away."
	done

_MoveFlavor_HYPNOSIS::
	text "A slow, patient"
	next "suggestion that"
	next "the foe should"
	next "stop."
	done

_MoveFlavor_ROCK_THROW::
	text "A stone picked up"
	next "and thrown. It"
	next "does not need to"
	next "be clever."
	done

_MoveFlavor_ROCK_PUNCH::
	text "A rock-solid blow"
	next "that leaves the"
	next "foe's guard"
	next "cracked."
	done

_MoveFlavor_ROCK_TOMB::
	text "Rocks dropped"
	next "around the foe"
	next "until there is"
	next "nowhere left to"
	next "move."
	done

_MoveFlavor_HEAD_SMASH::
	text "The user leads"
	next "with its head and"
	next "does not spare"
	next "itself at all."
	done

_MoveFlavor_ROCK_SLIDE::
	text "The slope lets go."
	next "Everything above"
	next "the foe arrives at"
	next "once."
	done

_MoveFlavor_CLAMP::
	text "The shell closes"
	next "on the foe and"
	next "stays shut."
	done

_MoveFlavor_ROLLOUT::
	text "The user tucks in,"
	next "gets rolling, and"
	next "grows harder to"
	next "stop."
	done

_MoveFlavor_BONEMERANG::
	text "The bone is"
	next "thrown, strikes,"
	next "and comes back to"
	next "strike again."
	done

_MoveFlavor_CRABHAMMER::
	text "The big claw comes"
	next "down like a"
	next "hammer, because"
	next "that is what it"
	next "is."
	done

_MoveFlavor_HORN_DRILL::
	text "A hardened point"
	next "bored into the foe"
	next "until its guard"
	next "splits open."
	done

_MoveFlavor_CUT::
	text "A clean stroke,"
	next "made with whatever"
	next "the user keeps"
	next "sharp."
	done

_MoveFlavor_IRON_TAIL::
	text "The tail comes"
	next "round hard and"
	next "lands like a bar"
	next "of iron."
	done

_MoveFlavor_IRON_HEAD::
	text "The user leads"
	next "with its head, and"
	next "the head does not"
	next "give."
	done

_MoveFlavor_SONICBOOM::
	text "A shaped pulse"
	next "thrown at the foe."
	next "It carries the"
	next "same force always."
	done

_MoveFlavor_BULLET_PUNCH::
	text "A short, fast blow"
	next "that arrives"
	next "before anything"
	next "else can."
	done

_MoveFlavor_MAGNET_BOMB::
	text "A charged mass"
	next "that steers itself"
	next "in. Dodging is not"
	next "an option."
	done

_MoveFlavor_WATER_GUN::
	text "A hard, narrow jet"
	next "of water, spat"
	next "with some force."
	done

_MoveFlavor_AQUA_JET::
	text "The user rides its"
	next "own spray straight"
	next "at the foe."
	done

_MoveFlavor_BUBBLEBEAM::
	text "A stream of"
	next "bubbles, harder on"
	next "arrival than they"
	next "look."
	done

_MoveFlavor_WATER_PULSE::
	text "A ring of pressure"
	next "that travels out"
	next "and muddles what"
	next "it meets."
	done

_MoveFlavor_WATERFALL::
	text "The user climbs"
	next "the water and"
	next "comes down with"
	next "it."
	done

_MoveFlavor_SURF::
	text "A wave raised over"
	next "the whole field"
	next "and let fall."
	done

_MoveFlavor_HYDRO_PUMP::
	text "Water at a"
	next "pressure that"
	next "strips whatever it"
	next "is aimed at and"
	next "knocks it off its"
	next "footing."
	done

_MoveFlavor_TRI_ATTACK::
	text "Three points of"
	next "fire, ice and"
	next "current, loosed"
	next "together."
	done

_MoveFlavor_SWORDS_DANCE::
	text "A quick, sharp"
	next "routine that works"
	next "the fighting"
	next "spirit up."
	done

_MoveFlavor_BULK_UP::
	text "The user tenses"
	next "all over, stronger"
	next "and harder to"
	next "hurt."
	done

_MoveFlavor_COIL::
	text "The user winds its"
	next "length tight,"
	next "ready to spring."
	done

_MoveFlavor_FIERCE_ROAR::
	text "A roar with real"
	next "threat in it, and"
	next "the foe hears the"
	next "threat."
	done

_MoveFlavor_HONE_CLAWS::
	text "The user hones its"
	next "weapons and takes"
	next "better aim."
	done
