; v0.7: MOVE INFO flavour, one entry per move.
;
; Printed above the shared mechanics block. Unlike the mechanics -- keyed to the
; effect on purpose, so two moves that behave alike read alike -- every one of
; these is written for its own move.
;
; Two rules shaped them. The move's NAME has to land: GORE ATTACK reads as
; bloody because that is what it is called. And the ANATOMY has to fit EVERY
; Pokemon that learns it -- TACKLE cannot be "a shoulder charge" when MAGIKARP
; knows it, and NUZZLE cannot mention cheeks when TENTACOOL does.
;
; Generated by .claude/flavor_build.py from prose; do not hand-edit the line
; breaks here, edit the prose and re-run.

; Part 3 of 5.

_MoveFlavor_RAZOR_LEAF::
	text "Leaves thrown"
	next "edge-first, stiff"
	next "enough to cut."
	done

_MoveFlavor_GIGA_DRAIN::
	text "The user drains"
	next "deeply, and is"
	next "visibly the better"
	next "for it."
	done

_MoveFlavor_PETAL_DANCE::
	text "The user whirls"
	next "through a storm of"
	next "petals and cannot"
	next "stop itself."
	done

_MoveFlavor_SOLARBEAM::
	text "Sunlight gathered"
	next "over a turn and"
	next "let go in a single"
	next "searing line."
	done

_MoveFlavor_LEECH_SEED::
	text "A seed takes root"
	next "on the foe and"
	next "feeds the user"
	next "from a distance."
	done

_MoveFlavor_POISONPOWDER::
	text "A dusting of"
	next "spores that works"
	next "in and turns the"
	next "blood."
	done

_MoveFlavor_STUN_POWDER::
	text "A powder that sets"
	next "the muscles"
	next "arguing with each"
	next "other."
	done

_MoveFlavor_SLEEP_POWDER::
	text "A powder that"
	next "settles quietly"
	next "and closes the"
	next "eyes."
	done

_MoveFlavor_GROUND_STOMP::
	text "The user brings"
	next "its weight down"
	next "hard enough to"
	next "shake the footing."
	done

_MoveFlavor_MUD_SHOT::
	text "A spatter of wet"
	next "grit, thrown for"
	next "the eyes as much"
	next "as anything."
	done

_MoveFlavor_BULLDOZE::
	text "The user drives"
	next "forward low and"
	next "shoves the ground"
	next "along with it."
	done

_MoveFlavor_MUD_BOMB::
	text "A packed lump of"
	next "mud, thrown heavy"
	next "and bursting on"
	next "impact."
	done

_MoveFlavor_EARTHQUAKE::
	text "The ground itself"
	next "is made to buck,"
	next "and there is"
	next "nowhere to stand."
	done

_MoveFlavor_FISSURE::
	text "The ground opens"
	next "under the foe."
	next "What falls in does"
	next "not climb out."
	done

_MoveFlavor_BONE_CLUB::
	text "The bone comes"
	next "down in a short,"
	next "heavy arc, held"
	next "two-handed."
	done

_MoveFlavor_DIG::
	text "The user goes"
	next "under and comes up"
	next "beneath the foe."
	done

_MoveFlavor_POWDER_SNOW::
	text "A breath of dry"
	next "snow that settles"
	next "and starts to"
	next "bite."
	done

_MoveFlavor_ICY_WIND::
	text "A cold wind that"
	next "stiffens whatever"
	next "it passes over."
	done

_MoveFlavor_FROST_BREATH::
	text "A breath cold"
	next "enough to leave"
	next "frost where it"
	next "lands."
	done

_MoveFlavor_ICY_PULSE::
	text "A cold that"
	next "travels through"
	next "the foe rather"
	next "than over it."
	done

_MoveFlavor_AURORA_BEAM::
	text "A band of shifting"
	next "colour, and a"
	next "chill behind it."
	done

_MoveFlavor_ICE_BEAM::
	text "A narrow beam that"
	next "freezes what it"
	next "touches solid."
	done

_MoveFlavor_BLIZZARD::
	text "A storm called up"
	next "over the whole"
	next "field, blind and"
	next "freezing."
	done

_MoveFlavor_MAGMA_PUNCH::
	text "A blow landed with"
	next "the heat of"
	next "something molten"
	next "behind it."
	done

_MoveFlavor_LAVA_PLUME::
	text "Molten rock thrown"
	next "up in a sheet and"
	next "left to fall where"
	next "it will."
	done

_MoveFlavor_WRAP::
	text "The user winds"
	next "itself around the"
	next "foe and does not"
	next "let go."
	done

_MoveFlavor_FURY_ATTACK::
	text "Quick, repeated"
	next "jabs that land"
	next "more often than"
	next "not."
	done

_MoveFlavor_SCRATCH::
	text "A short raking"
	next "strike. Simple,"
	next "and it works."
	done

_MoveFlavor_TACKLE::
	text "The user throws"
	next "itself bodily at"
	next "the foe. Nothing"
	next "more to it."
	done

_MoveFlavor_BITE::
	text "The jaws close"
	next "hard and do not"
	next "open straight"
	next "away."
	done

_MoveFlavor_QUICK_ATTACK::
	text "The user is across"
	next "the gap before the"
	next "foe has finished"
	next "looking."
	done

_MoveFlavor_HEADBUTT::
	text "The user leads"
	next "with the hardest"
	next "part of itself."
	done

_MoveFlavor_HORN_ATTACK::
	text "The horn is put"
	next "where it will do"
	next "most, in one clean"
	next "thrust."
	done

_MoveFlavor_SLASH::
	text "A long, drawn cut,"
	next "delivered fast and"
	next "aimed well."
	done

_MoveFlavor_BODY_SLAM::
	text "The user drops its"
	next "full weight onto"
	next "the foe and stays"
	next "there a moment."
	done

_MoveFlavor_CRUNCH::
	text "One heavy bite,"
	next "hard enough to"
	next "leave the foe's"
	next "guard cracked."
	done

_MoveFlavor_HORN_CHARGE::
	text "A run from a"
	next "distance with the"
	next "horn levelled the"
	next "whole way."
	done

_MoveFlavor_THRASH::
	text "The user flails"
	next "with everything it"
	next "has and no plan."
	done

_MoveFlavor_HEAVY_SLAM::
	text "The user brings"
	next "its full bulk"
	next "down. Weight does"
	next "the work."
	done

_MoveFlavor_DOUBLE_EDGE::
	text "A charge held"
	next "nothing back, and"
	next "the user feels it"
	next "afterwards."
	done

_MoveFlavor_EXTREMESPEED::
	text "The user is simply"
	next "there, and then"
	next "the blow has"
	next "landed."
	done

_MoveFlavor_SUPERSONIC::
	text "A note pitched to"
	next "unsettle the sense"
	next "of balance."
	done

_MoveFlavor_SUPER_FANG::
	text "Front teeth built"
	next "to gnaw through"
	next "anything, used on"
	next "the foe."
	done

_MoveFlavor_HYPER_FANG::
	text "One deep bite, put"
	next "where it will"
	next "matter most."
	done

_MoveFlavor_FALSE_SWIPE::
	text "The blow is pulled"
	next "just short of the"
	next "kill."
	done

_MoveFlavor_POISON_STING::
	text "A small, sharp"
	next "jab, and the venom"
	next "does the rest."
	done
