; v0.7: MOVE INFO flavour, one entry per move.
;
; Printed above the shared mechanics block. Unlike the mechanics -- keyed to the
; effect on purpose, so two moves that behave alike read alike -- every one of
; these is written for its own move.
;
; Two rules shaped them. The move's NAME has to land: GORE ATTACK reads as
; bloody because that is what it is called. And the ANATOMY has to fit EVERY
; Pokemon that learns it -- TACKLE cannot be "a shoulder charge" when MAGIKARP
; knows it, and NUZZLE cannot mention cheeks when TENTACOOL does.
;
; Generated by .claude/flavor_build.py from prose; do not hand-edit the line
; breaks here, edit the prose and re-run.

; Part 1 of 5.

_MoveFlavor_CONSTRICT::
	text "Whatever the user"
	next "can wrap around"
	next "the foe closes on"
	next "it and draws"
	next "slowly tight."
	done

_MoveFlavor_BUG_BITE::
	text "Mouthparts made"
	next "for stems and bark"
	next "close on the foe"
	next "instead."
	done

_MoveFlavor_LEECH_LIFE::
	text "A feeding wound."
	next "The user leaves it"
	next "heavier than it"
	next "came."
	done

_MoveFlavor_BUG_BUZZ::
	text "Wings beat a note"
	next "too low to hear."
	next "It is felt, not"
	next "heard."
	done

_MoveFlavor_MEGAHORN::
	text "A charge with the"
	next "head down and the"
	next "whole weight of"
	next "the body behind"
	next "one horn."
	done

_MoveFlavor_GUILLOTINE::
	text "Blades close once,"
	next "meant to shear"
	next "through rather"
	next "than crush."
	done

_MoveFlavor_VICEGRIP::
	text "Pincers take hold"
	next "and grind until"
	next "something gives."
	done

_MoveFlavor_TWINEEDLE::
	text "Both lances go in,"
	next "one then the"
	next "other, each with"
	next "its own dose."
	done

_MoveFlavor_FAINT_ATTACK::
	text "The user closes"
	next "without a sound"
	next "and is already"
	next "striking when the"
	next "foe finds it."
	done

_MoveFlavor_RAGE::
	text "Temper takes over."
	next "Every blow the"
	next "user takes only"
	next "feeds it."
	done

_MoveFlavor_NIGHT_SLASH::
	text "A cutting stroke"
	next "out of the dark,"
	next "aimed where the"
	next "guard is thinnest."
	done

_MoveFlavor_BRUTAL_SWING::
	text "The user swings"
	next "its whole body"
	next "round like a club,"
	next "with no thought"
	next "for aim."
	done

_MoveFlavor_DARK_PULSE::
	text "Something cold and"
	next "wrong washes over"
	next "the foe and leaves"
	next "it shaken."
	done

_MoveFlavor_GORE_ATTACK::
	text "The user drives in"
	next "and tears, and"
	next "does not stop"
	next "while anything"
	next "still moves."
	done

_MoveFlavor_PAY_DAY::
	text "Coins flung hard"
	next "enough to sting,"
	next "and left lying"
	next "where they fall."
	done

_MoveFlavor_DREAM_EATER::
	text "The user leans"
	next "over a sleeping"
	next "foe and eats the"
	next "dream whole."
	done

_MoveFlavor_DEEP_SLEEP::
	text "A weight behind"
	next "the eyes until"
	next "they will not open"
	next "again."
	done

_MoveFlavor_DRAGON_RAGE::
	text "A short, furious"
	next "blast, spat"
	next "without aim. It"
	next "never varies."
	done

_MoveFlavor_DRAGON_CLAW::
	text "A dragon's strike,"
	next "raking down"
	next "through the guard"
	next "in one pass."
	done

_MoveFlavor_DRAGON_BREATH::
	text "A breath charged"
	next "enough to lift the"
	next "hair on anything"
	next "near it."
	done

_MoveFlavor_DRAGON_SLAM::
	text "The user throws"
	next "its whole length"
	next "at the foe and"
	next "takes the impact"
	next "with it."
	done

_MoveFlavor_OUTRAGE::
	text "The user goes"
	next "berserk, tearing"
	next "until the fury"
	next "burns out."
	done

_MoveFlavor_HYPER_BEAM::
	text "Everything the"
	next "user has, loosed"
	next "at once in a beam"
	next "that scours."
	done

_MoveFlavor_NUZZLE::
	text "The user presses"
	next "close and lets the"
	next "charge it holds"
	next "earth out through"
	next "the foe."
	done

_MoveFlavor_THUNDERSHOCK::
	text "A small jolt, more"
	next "startling than"
	next "damaging."
	done

_MoveFlavor_SHOCK_WAVE::
	text "A charge that"
	next "finds its own way"
	next "across. There is"
	next "no dodging it."
	done

_MoveFlavor_THUNDERBOLT::
	text "A hard, clean bolt"
	next "with the whole"
	next "charge behind it."
	done

_MoveFlavor_THUNDER::
	text "The sky splits and"
	next "comes down on the"
	next "foe."
	done

_MoveFlavor_THUNDER_WAVE::
	text "A current run"
	next "through the foe,"
	next "enough to spoil"
	next "its timing."
	done

_MoveFlavor_VOLT_TACKLE::
	text "The user charges"
	next "wrapped in its own"
	next "current, and"
	next "arrives with it."
	done

_MoveFlavor_DOUBLESLAP::
	text "A flurry of open"
	next "blows, stinging"
	next "rather than heavy."
	done

_MoveFlavor_FAIRY_WIND::
	text "A light wind that"
	next "ought to be"
	next "harmless, and is"
	next "not."
	done

_MoveFlavor_DRAINING_KISS::
	text "A touch that takes"
	next "more than it"
	next "gives."
	done

_MoveFlavor_DAZZLE_GLEAM::
	text "A burst of light"
	next "too bright to look"
	next "away from."
	done

_MoveFlavor_PLAY_ROUGH::
	text "The user tumbles"
	next "the foe about as"
	next "if playing, and"
	next "forgets its"
	next "strength."
	done

_MoveFlavor_LOVELY_KISS::
	text "A fond kiss,"
	next "offered"
	next "mid-battle. The"
	next "foe is left too"
	next "bewildered to"
	next "think."
	done

_MoveFlavor_SING::
	text "A steady,"
	next "wandering tune."
	next "The eyelids go"
	next "first."
	done

_MoveFlavor_MOONBLAST::
	text "Moonlight gathered"
	next "over a turn and"
	next "let go in a single"
	next "cold burst."
	done

_MoveFlavor_SEISMIC_TOSS::
	text "The foe is lifted,"
	next "swung round and"
	next "put through the"
	next "ground."
	done

_MoveFlavor_LOW_KICK::
	text "A blow struck low,"
	next "where the weight"
	next "is and the guard"
	next "is not."
	done

_MoveFlavor_COMET_PUNCH::
	text "Blows land two and"
	next "three at a time,"
	next "faster than they"
	next "can be counted."
	done

_MoveFlavor_BIND::
	text "The user takes"
	next "hold and squeezes,"
	next "and the grip"
	next "leaves the foe"
	next "stiff."
	done
