; v0.7: MOVE INFO flavour, one entry per move.
;
; Printed above the shared mechanics block. Unlike the mechanics -- keyed to the
; effect on purpose, so two moves that behave alike read alike -- every one of
; these is written for its own move.
;
; Two rules shaped them. The move's NAME has to land: GORE ATTACK reads as
; bloody because that is what it is called. And the ANATOMY has to fit EVERY
; Pokemon that learns it -- TACKLE cannot be "a shoulder charge" when MAGIKARP
; knows it, and NUZZLE cannot mention cheeks when TENTACOOL does.
;
; Generated by .claude/flavor_build.py from prose; do not hand-edit the line
; breaks here, edit the prose and re-run.

; Part 2 of 5.

_MoveFlavor_MACH_PUNCH::
	text "The blow lands"
	next "before the choice"
	next "to throw it looks"
	next "finished."
	done

_MoveFlavor_KARATE_CHOP::
	text "One edged strike,"
	next "placed where the"
	next "bone runs closest."
	done

_MoveFlavor_STRENGTH::
	text "The user sets"
	next "itself, finds its"
	next "footing, and hits"
	next "harder for it."
	done

_MoveFlavor_TAKE_DOWN::
	text "A charge that goes"
	next "straight through"
	next "the foe and leaves"
	next "it shaken."
	done

_MoveFlavor_LEEK_STRIKE::
	text "The stalk comes"
	next "round in a short,"
	next "practised arc. It"
	next "is held like a"
	next "weapon."
	done

_MoveFlavor_DIZZY_PUNCH::
	text "Blows land out of"
	next "rhythm until the"
	next "foe loses which"
	next "way is up."
	done

_MoveFlavor_ROLLING_KICK::
	text "The user turns"
	next "through the strike"
	next "and puts the spin"
	next "into the foot."
	done

_MoveFlavor_SUBMISSION::
	text "The user locks on"
	next "and drives the foe"
	next "into the ground,"
	next "guard and all."
	done

_MoveFlavor_SKY_UPPERCUT::
	text "A blow that starts"
	next "low and finishes"
	next "overhead,"
	next "following the foe"
	next "up."
	done

_MoveFlavor_HI_JUMP_KICK::
	text "The user leaps and"
	next "comes down knee"
	next "first, from an"
	next "unlikely height."
	done

_MoveFlavor_EMBER::
	text "A short, spat"
	next "flame. Small, but"
	next "hot where it"
	next "lands."
	done

_MoveFlavor_FLAME_CHARGE::
	text "The user runs at"
	next "the foe wrapped in"
	next "fire, and comes"
	next "out moving faster."
	done

_MoveFlavor_FLAME_BURST::
	text "A ball of fire"
	next "that bursts on"
	next "contact and throws"
	next "the rest outward."
	done

_MoveFlavor_FLAMETHROWER::
	text "A long, steady jet"
	next "of flame, held"
	next "long enough to"
	next "matter."
	done

_MoveFlavor_FIRE_BLAST::
	text "Fire loosed in a"
	next "broad, wasteful"
	next "bloom that"
	next "swallows what is"
	next "in front of it."
	done

_MoveFlavor_IGNITE::
	text "A flame set on the"
	next "foe and left to do"
	next "its work."
	done

_MoveFlavor_EXPLOSION::
	text "The user"
	next "detonates, and all"
	next "it ever had goes"
	next "up with it."
	done

_MoveFlavor_PECK::
	text "A short jab of the"
	next "beak, quick and to"
	next "the point."
	done

_MoveFlavor_GUST::
	text "One hard beat of"
	next "the wings, aimed"
	next "rather than flown"
	next "with."
	done

_MoveFlavor_WING_ATTACK::
	text "The wing comes"
	next "round edge-on and"
	next "is harder than it"
	next "looks."
	done

_MoveFlavor_AERIAL_ACE::
	text "The user comes in"
	next "at an angle the"
	next "foe cannot cover"
	next "in time."
	done

_MoveFlavor_FLY::
	text "The user takes to"
	next "the air, waits,"
	next "and drops out of"
	next "it."
	done

_MoveFlavor_HURRICANE::
	text "Wind pulled into a"
	next "turning wall and"
	next "pushed at the foe."
	done

_MoveFlavor_SKY_ATTACK::
	text "The user climbs"
	next "from sight and"
	next "falls like a"
	next "dropped anvil."
	done

_MoveFlavor_DRILL_PECK::
	text "A spinning point"
	next "driven in and kept"
	next "turning."
	done

_MoveFlavor_SPORE_DAZE::
	text "Spores settle in"
	next "the air and are"
	next "breathed before"
	next "they are noticed."
	done

_MoveFlavor_PARASITE::
	text "The mushroom takes"
	next "what it needs, as"
	next "it always has."
	done

_MoveFlavor_SPORE::
	text "A fine dust that"
	next "puts anything"
	next "breathing it"
	next "straight to sleep."
	done

_MoveFlavor_SMOG::
	text "A thick, foul"
	next "cloud that gets"
	next "everywhere and"
	next "stays there."
	done

_MoveFlavor_HAZE::
	text "A grey fog rolls"
	next "over the field and"
	next "everything gained"
	next "is lost in it."
	done

_MoveFlavor_POISON_GAS::
	text "A quiet,"
	next "colourless cloud."
	next "The foe notices it"
	next "too late."
	done

_MoveFlavor_NIGHT_SHADE::
	text "A shape out of the"
	next "dark that hurts as"
	next "much as the user"
	next "is old."
	done

_MoveFlavor_LICK::
	text "Something wet"
	next "drags across the"
	next "foe, and the"
	next "shudder does the"
	next "rest."
	done

_MoveFlavor_ASTONISH::
	text "A sudden noise"
	next "from nowhere. The"
	next "foe jumps before"
	next "it thinks."
	done

_MoveFlavor_SHADOW_SNEAK::
	text "The user's shadow"
	next "reaches the foe"
	next "well before the"
	next "user does."
	done

_MoveFlavor_SHADOW_PUNCH::
	text "A blow thrown out"
	next "of the dark that"
	next "no guard seems to"
	next "meet."
	done

_MoveFlavor_SPIRIT_DRAIN::
	text "Cold fingers close"
	next "on whatever keeps"
	next "the foe alive, and"
	next "pull."
	done

_MoveFlavor_SHADOW_BALL::
	text "A knot of shadow"
	next "thrown hard and"
	next "left to burst."
	done

_MoveFlavor_CONFUSE_RAY::
	text "A light that will"
	next "not hold still."
	next "Watching it is the"
	next "mistake."
	done

_MoveFlavor_WILL_O_WISP::
	text "A pale flame set"
	next "drifting. It finds"
	next "the foe on its"
	next "own."
	done

_MoveFlavor_ABSORB::
	text "The user draws a"
	next "little of the"
	next "foe's strength"
	next "into itself."
	done

_MoveFlavor_VINE_WHIP::
	text "A vine cracks"
	next "across the foe"
	next "like a lash,"
	next "stinging where it"
	next "lands."
	done

_MoveFlavor_MEGA_DRAIN::
	text "The user takes a"
	next "good deal of the"
	next "foe's strength for"
	next "itself."
	done
