; GENERATED by .claude/manual_build.py. The prose lives there;
; this file is only the line-breaking. Do not hand-edit.
;
; A page holds 13 lines of 18 tiles, with `#` rendering as the four
; characters of "POKé". Blank lines go between paragraphs while the
; page has room and are dropped from the bottom when it is full.
;
; ManualPage_5_2 has a _Hard twin: the PP page is the second place in
; the game to read wDifficulty and tell the truth for each setting.
; See TrainerManualHardPages in engine/menus/trainer_manual.asm.

_ManualPage_1_1::
	text "The BAG carries"
	next "what you own."
	next ""
	next "Press SELECT on an"
	next "item to lift it,"
	next "and SELECT again"
	next "to set it down"
	next "somewhere else."
	next ""
	next "Press START to"
	next "sort the whole BAG"
	next "at once."
	done

_ManualPage_1_2::
	text "Choose INFO on any"
	next "item you carry to"
	next "read what it does."
	next ""
	next "Every item has an"
	next "entry, and most"
	next "trainers never"
	next "look."
	done

_ManualPage_1_3::
	text "For an item you do"
	next "not carry, the"
	next "CELADON DEPT."
	next "STORE keeps an"
	next "information desk"
	next "on its first"
	next "floor."
	done

_ManualPage_1_4::
	text "Press START on the"
	next "FIGHT menu to read"
	next "the move under the"
	next "cursor: its TYPE,"
	next "its POWER, its"
	next "ACCURACY, its PP"
	next "and what it does."
	next ""
	next "The same card"
	next "opens when a"
	next "#MON is offered"
	next "a new move."
	done

_ManualPage_1_5::
	text "Press START in the"
	next "#DEX to turn to"
	next "the MOVES list."
	next ""
	next "It holds every"
	next "move in KANTO, and"
	next "fills in as you"
	next "watch them used."
	done

_ManualPage_2_1::
	text "Wild #MON live"
	next "in tall grass, and"
	next "in water while you"
	next "SURF."
	next ""
	next "A ROD brings up"
	next "what swims deeper."
	next ""
	next "Underground they"
	next "are everywhere,"
	next "and every step in"
	next "a cave may turn"
	next "one up."
	done

_ManualPage_2_2::
	text "A #MON at full"
	next "health shrugs off"
	next "a BALL. Wear it"
	next "down, or put it to"
	next "sleep, before you"
	next "throw."
	next ""
	next "A #MON you"
	next "catch pays"
	next "experience, half"
	next "of what beating it"
	next "would."
	done

_ManualPage_2_3::
	text "Every #MON MART"
	next "stocks more as"
	next "your badges pile"
	next "up."
	next ""
	next "Visit again after"
	next "every GYM."
	done

_ManualPage_2_4::
	text "In the LAB on"
	next "CINNABAR ISLAND"
	next "one man will make"
	next "a #MON forget a"
	next "move, and another"
	next "will teach it one"
	next "it knew before."
	next ""
	next "Nothing is lost"
	next "for good."
	done

_ManualPage_2_5::
	text "Three things you"
	next "do make a BALL"
	next "land."
	next ""
	next "How hurt it is."
	next "Under a tenth,"
	next "three times as"
	next "likely."
	next "What ails it."
	next "SLEEP nearly"
	next "doubles it."
	next "Which BALL. GREAT"
	next "two, ULTRA three."
	done

_ManualPage_2_6::
	text "Only the worst"
	next "thing counts. They"
	next "do not stack."
	next ""
	next "Confusion counts,"
	next "though no screen"
	next "shows it."
	next ""
	next "POISON, BURN,"
	next "TOXIC and"
	next "confusion all take"
	next "health, and will"
	next "finish the job."
	done

_ManualPage_3_1::
	text "SPECIAL does two"
	next "jobs at once."
	next ""
	next "It is the power"
	next "behind your"
	next "special moves and"
	next "the wall against"
	next "theirs."
	done

_ManualPage_3_2::
	text "No two #MON are"
	next "truly alike."
	next ""
	next "On the STATS page,"
	next "hold START to see"
	next "what one was born"
	next "with."
	next ""
	next "Hold SELECT to see"
	next "what it has earned"
	next "in battle."
	done

_ManualPage_3_3::
	text "Species climb at"
	next "their own pace."
	next ""
	next "Two #MON at the"
	next "same level may"
	next "have needed very"
	next "different work."
	done

_ManualPage_3_4::
	text "Four badges"
	next "strengthen your"
	next "#MON."
	next ""
	next "BOULDER lifts"
	next "ATTACK. THUNDER"
	next "lifts DEFENSE."
	next "SOUL lifts SPEED."
	next "VOLCANO lifts"
	next "SPECIAL."
	next ""
	next "A PIKACHU takes"
	next "twice that boost."
	done

_ManualPage_3_5::
	text "The EXP.SHARE"
	next "moves experience;"
	next "it makes none."
	next ""
	next "ONE: half of every"
	next "reward goes to"
	next "your last #MON."
	next ""
	next "TEAM: it is split"
	next "among all who can"
	next "gain."
	next ""
	next "Catching pays too."
	done

_ManualPage_4_1::
	text "PARALYSIS cuts"
	next "SPEED in half,"
	next "never below one"
	next "point."
	next ""
	next "One turn in four"
	next "is lost to it."
	next ""
	next "It stays after the"
	next "battle. A"
	next "PARALYSIS HEAL or"
	next "a FULL HEAL clears"
	next "it."
	done

_ManualPage_4_2::
	text "A BURN cuts ATTACK"
	next "in half and bites"
	next "for an eighth of"
	next "full health each"
	next "turn."
	next ""
	next "It stays after the"
	next "battle. BURN HEAL"
	next "or a FULL HEAL"
	next "clears it."
	done

_ManualPage_4_3::
	text "FREEZE holds a"
	next "#MON still for"
	next "three to six"
	next "turns, then thaws"
	next "on its own."
	next ""
	next "A FIRE or MAGMA"
	next "hit thaws it at"
	next "once. So does an"
	next "ICE HEAL or a FULL"
	next "HEAL."
	done

_ManualPage_4_4::
	text "SLEEP holds a"
	next "#MON still for"
	next "two to five turns."
	next ""
	next "It stays after the"
	next "battle. A SLEEP"
	next "HEAL or a FULL"
	next "HEAL wakes them"
	next "early."
	done

_ManualPage_4_5::
	text "POISON bites for"
	next "an eighth of full"
	next "health each turn,"
	next "in battle and out."
	next ""
	next "A bad POISON bites"
	next "harder each turn."
	next "Calling it back"
	next "leaves ordinary"
	next "POISON."
	next "A POISON HEAL or a"
	next "FULL HEAL clears"
	next "both."
	done

_ManualPage_4_6::
	text "CONFUSION lasts"
	next "two to five turns."
	next ""
	next "Half the time the"
	next "#MON strikes"
	next "itself instead."
	next ""
	next "A FULL HEAL or a"
	next "FULL RESTORE"
	next "clears it, and so"
	next "does calling it"
	next "back."
	done

_ManualPage_4_7::
	text "Call one back and"
	next "it forgets"
	next "confusion, every"
	next "raised or lowered"
	next "stat, and any"
	next "guard it had up."
	next ""
	next "SLEEP, POISON,"
	next "BURN, PARALYSIS"
	next "and FREEZE travel"
	next "with it."
	done

_ManualPage_4_8::
	text "FIRE and MAGMA"
	next "never burn. ICE"
	next "and MAGMA never"
	next "freeze."
	next ""
	next "ELECTRIC never"
	next "takes PARALYSIS."
	next "POISON and STEEL"
	next "never take POISON."
	next ""
	next "Types that cannot"
	next "be hit at all are"
	next "in THE TYPES."
	done

_ManualPage_4_9::
	text "GUARD SPEC. keeps"
	next "your STATS from"
	next "being cut."
	next ""
	next "It does nothing"
	next "about SLEEP,"
	next "POISON or the"
	next "rest."
	done

_ManualPage_5_1::
	text "Every move has a"
	next "limited number of"
	next "uses, called PP."
	next ""
	next "Restore it at a"
	next "#MON CENTER, or"
	next "with an ETHER."
	done

_ManualPage_5_2::
	text "Their team spends"
	next "PP as yours does."
	next ""
	next "Outlast one and it"
	next "must STRUGGLE, and"
	next "hurt itself doing"
	next "it."
	done

_ManualPage_5_2_Hard::
	text "A trainer's team"
	next "never runs dry."
	next ""
	next "Waiting one out"
	next "will not work."
	next "Carry the fight"
	next "instead."
	done

_ManualPage_5_3::
	text "An X item or a"
	next "move lifts a stat"
	next "one step, or drops"
	next "a foe's by one."
	next ""
	next "Six either way is"
	next "the limit."
	next "Calling a #MON"
	next "back gives every"
	next "step back. A"
	next "critical hit"
	next "ignores the steps"
	next "set against it."
	done

_ManualPage_5_4::
	text "ACCURACY and"
	next "EVASION move in"
	next "steps too."
	next ""
	next "One step is a"
	next "small edge. Stack"
	next "them and the edge"
	next "grows fast."
	done

_ManualPage_5_5::
	text "Any move may land"
	next "a critical hit,"
	next "dealing half again"
	next "its damage."
	next ""
	next "The chance is ten"
	next "in a hundred, plus"
	next "one for every ten"
	next "points of the"
	next "attacker's base"
	next "SPEED."
	next "Sharp moves start"
	next "at twenty."
	done

_ManualPage_5_6::
	text "FOCUS ENERGY"
	next "TRIPLES your"
	next "chance of a"
	next "critical hit, and"
	next "lifts your aim by"
	next "one step."
	next ""
	next "It holds until"
	next "that #MON is"
	next "called back."
	done

_ManualPage_6_1::
	text "KANTO knows more"
	next "types than a"
	next "trainer may"
	next "expect."
	next ""
	next "Beside the"
	next "familiar ones"
	next "stand DARK, STEEL,"
	next "MAGMA, FUNGUS,"
	next "FAIRY and GAS."
	done

_ManualPage_6_2::
	text "A move strikes"
	next "with the body or"
	next "with the mind, and"
	next "its TYPE decides"
	next "which."
	next ""
	next "The body uses"
	next "ATTACK against"
	next "DEFENSE. The mind"
	next "uses SPECIAL"
	next "against SPECIAL."
	next "A move's card"
	next "names which."
	done

_ManualPage_6_3::
	text "A #MON may"
	next "carry two types."
	next "Both of them count"
	next "when a move lands"
	next "on it."
	next ""
	next "And a move of"
	next "either of its own"
	next "types hits half"
	next "again as hard."
	done

_ManualPage_6_4::
	text "These strike with"
	next "the body:"
	next ""
	next "NORMAL FIGHTING"
	next "FLYING POISON"
	next "GROUND ROCK BUG"
	next "DRAGON DARK STEEL"
	next "MAGMA FUNGUS."
	done

_ManualPage_6_5::
	text "And these with the"
	next "mind:"
	next ""
	next "GHOST FIRE WATER"
	next "GRASS ELECTRIC"
	next "PSYCHIC ICE FAIRY"
	next "GAS."
	done

_ManualPage_7_1::
	text "This journey is"
	next "walked on one of"
	next "two settings,"
	next "chosen the day it"
	next "begins."
	next ""
	next "The OPTION menu"
	next "will tell you"
	next "which one you are"
	next "on."
	done

_ManualPage_7_2::
	text "On the harder"
	next "setting a"
	next "trainer's team"
	next "never runs dry of"
	next "PP."
	next ""
	next "REVIVE, ETHER and"
	next "ELIXIR, and their"
	next "greater forms, are"
	next "refused in a"
	next "trainer battle."
	next "Wild ones are not."
	done

_ManualPage_7_3::
	text "On the harder"
	next "setting a #MON"
	next "that faints earns"
	next "nothing from that"
	next "fight."
	next ""
	next "Every other reward"
	next "of experience is a"
	next "little smaller."
	done

_ManualPage_7_4::
	text "GYM LEADERS, the"
	next "ELITE FOUR and"
	next "your rival are"
	next "even harder there."
	next ""
	next "They carry items"
	next "and spend them."
	next "They stand a level"
	next "above and crit"
	next "more often."
	next "Their moves land"
	next "more often, and"
	next "yours less."
	done

