; GENERATED by .claude/manual_types_build.py from
; data/types/type_matchups.asm. Do not hand-edit: the point of
; generating it is that the TRAINER MANUAL cannot disagree with the
; table the battle engine reads. Re-run after changing a matchup.

_ManualType_NORMAL_ATK::
	text "AS AN ATTACKER"
	next "WEAK AGAINST"
	next "ROCK FIGHTING"
	next "STEEL DARK GAS"
	next "MAGMA"
	next ""
	next "CANNOT HIT"
	next "GHOST"
	done

_ManualType_NORMAL_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "FIGHTING DARK"
	done

_ManualType_FIGHTING_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "ICE ROCK DRAGON"
	next "DARK STEEL NORMAL"
	next ""
	next "WEAK AGAINST"
	next "POISON FLYING"
	next "PSYCHIC BUG FAIRY"
	next ""
	next "CANNOT HIT"
	next "GHOST"
	done

_ManualType_FIGHTING_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "FLYING PSYCHIC"
	next "FAIRY"
	next ""
	next "RESISTS"
	next "NORMAL POISON BUG"
	next "ROCK DARK STEEL"
	done

_ManualType_FLYING_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "GRASS FIGHTING BUG"
	next "GAS"
	next ""
	next "WEAK AGAINST"
	next "ELECTRIC ROCK"
	next "STEEL"
	done

_ManualType_FLYING_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "ELECTRIC ICE ROCK"
	next "STEEL"
	next ""
	next "RESISTS"
	next "GRASS FIGHTING BUG"
	next "GAS"
	next ""
	next "IMMUNE TO"
	next "GROUND"
	done

_ManualType_POISON_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "GRASS BUG FAIRY"
	next "FUNGUS"
	next ""
	next "WEAK AGAINST"
	next "POISON GROUND ROCK"
	next "GHOST PSYCHIC ICE"
	next "FIGHTING MAGMA"
	next ""
	next "CANNOT HIT"
	next "STEEL"
	done

_ManualType_POISON_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "GROUND"
	next ""
	next "RESISTS"
	next "GRASS FIGHTING"
	next "POISON FAIRY"
	next "FUNGUS"
	done

_ManualType_GROUND_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "FIRE ELECTRIC"
	next "POISON ROCK STEEL"
	next "MAGMA"
	next ""
	next "WEAK AGAINST"
	next "GRASS BUG GHOST"
	next "FUNGUS"
	next ""
	next "CANNOT HIT"
	next "FLYING GAS"
	done

_ManualType_GROUND_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "WATER GRASS ICE"
	next ""
	next "RESISTS"
	next "FIRE POISON ROCK"
	next "MAGMA"
	next ""
	next "IMMUNE TO"
	next "ELECTRIC"
	done

_ManualType_ROCK_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "ICE FLYING BUG"
	next ""
	next "WEAK AGAINST"
	next "FIGHTING GROUND"
	next "STEEL GAS"
	done

_ManualType_ROCK_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "WATER GRASS"
	next "FIGHTING GROUND"
	next "STEEL"
	next ""
	next "RESISTS"
	next "NORMAL FIRE"
	next "ELECTRIC POISON"
	next "FLYING BUG GAS"
	done

_ManualType_BUG_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "GRASS PSYCHIC DARK"
	next "GHOST"
	next ""
	next "WEAK AGAINST"
	next "FIRE FIGHTING"
	next "FLYING ROCK STEEL"
	next "FAIRY GAS MAGMA"
	next "FUNGUS"
	done

_ManualType_BUG_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "FIRE ELECTRIC ICE"
	next "POISON FLYING ROCK"
	next "GAS MAGMA FUNGUS"
	next ""
	next "RESISTS"
	next "GRASS FIGHTING"
	next "GROUND GHOST"
	next "PSYCHIC DARK"
	done

_ManualType_DRAGON_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "DRAGON"
	next ""
	next "WEAK AGAINST"
	next "STEEL FAIRY"
	done

_ManualType_DRAGON_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "ICE FIGHTING"
	next "DRAGON STEEL FAIRY"
	next ""
	next "RESISTS"
	next "FIRE WATER GRASS"
	next "ELECTRIC MAGMA"
	done

_ManualType_DARK_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "PSYCHIC GHOST"
	next "NORMAL"
	next ""
	next "WEAK AGAINST"
	next "FIGHTING DARK"
	next "FAIRY BUG"
	done

_ManualType_DARK_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "FIGHTING BUG GHOST"
	next "FAIRY"
	next ""
	next "RESISTS"
	next "NORMAL DARK"
	next ""
	next "IMMUNE TO"
	next "PSYCHIC"
	done

_ManualType_STEEL_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "ICE ROCK DRAGON"
	next "FAIRY FLYING"
	next ""
	next "WEAK AGAINST"
	next "FIRE FIGHTING"
	next "ELECTRIC STEEL"
	next "MAGMA GAS"
	done

_ManualType_STEEL_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "FIRE ELECTRIC"
	next "FIGHTING GROUND"
	next "MAGMA"
	next ""
	next "RESISTS"
	next "NORMAL GRASS ICE"
	next "FLYING BUG ROCK"
	next "DRAGON STEEL FAIRY"
	next "GAS FUNGUS"
	next "IMMUNE TO"
	next "POISON"
	done

_ManualType_MAGMA_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "GRASS ICE BUG"
	next "STEEL FAIRY FUNGUS"
	next "GAS"
	next ""
	next "WEAK AGAINST"
	next "MAGMA DRAGON FIRE"
	next "GROUND"
	done

_ManualType_MAGMA_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "WATER GROUND"
	next ""
	next "RESISTS"
	next "NORMAL GRASS ICE"
	next "POISON BUG STEEL"
	next "GAS MAGMA FUNGUS"
	next ""
	next "IMMUNE TO"
	next "FIRE"
	done

_ManualType_FUNGUS_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "GRASS BUG"
	next ""
	next "WEAK AGAINST"
	next "FIRE ICE POISON"
	next "MAGMA STEEL"
	done

_ManualType_FUNGUS_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "FIRE ICE POISON"
	next "MAGMA"
	next ""
	next "RESISTS"
	next "WATER GRASS GROUND"
	next "BUG"
	done

_ManualType_GHOST_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "PSYCHIC DARK"
	next ""
	next "WEAK AGAINST"
	next "BUG GHOST"
	done

_ManualType_GHOST_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "BUG DARK"
	next ""
	next "RESISTS"
	next "POISON GROUND"
	next "GHOST GAS"
	next ""
	next "IMMUNE TO"
	next "NORMAL FIGHTING"
	done

_ManualType_FIRE_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "GRASS ICE BUG"
	next "STEEL FAIRY GAS"
	next "FUNGUS"
	next ""
	next "WEAK AGAINST"
	next "FIRE WATER ROCK"
	next "GROUND DRAGON"
	next ""
	next "CANNOT HIT"
	next "MAGMA"
	done

_ManualType_FIRE_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "WATER GROUND"
	next ""
	next "RESISTS"
	next "FIRE GRASS ICE BUG"
	next "STEEL FAIRY GAS"
	next "MAGMA FUNGUS"
	done

_ManualType_WATER_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "FIRE GROUND ROCK"
	next "MAGMA"
	next ""
	next "WEAK AGAINST"
	next "WATER GRASS GAS"
	next "DRAGON FUNGUS"
	done

_ManualType_WATER_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "GRASS ELECTRIC"
	next ""
	next "RESISTS"
	next "FIRE WATER"
	done

_ManualType_GRASS_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "WATER GROUND ROCK"
	next ""
	next "WEAK AGAINST"
	next "FIRE GRASS POISON"
	next "FLYING BUG STEEL"
	next "FAIRY MAGMA FUNGUS"
	next "DRAGON"
	done

_ManualType_GRASS_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "FIRE ICE POISON"
	next "FLYING BUG GAS"
	next "MAGMA FUNGUS"
	next ""
	next "RESISTS"
	next "WATER GRASS"
	next "ELECTRIC GROUND"
	done

_ManualType_ELECTRIC_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "WATER FLYING BUG"
	next "GAS STEEL"
	next ""
	next "WEAK AGAINST"
	next "GRASS ELECTRIC"
	next "ROCK DRAGON"
	next ""
	next "CANNOT HIT"
	next "GROUND"
	done

_ManualType_ELECTRIC_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "GROUND"
	next ""
	next "RESISTS"
	next "ELECTRIC FLYING"
	next "STEEL"
	done

_ManualType_PSYCHIC_TYPE_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "FIGHTING"
	next ""
	next "WEAK AGAINST"
	next "PSYCHIC BUG"
	next ""
	next "CANNOT HIT"
	next "DARK"
	done

_ManualType_PSYCHIC_TYPE_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "BUG GHOST DARK"
	next ""
	next "RESISTS"
	next "FIGHTING POISON"
	next "PSYCHIC"
	done

_ManualType_ICE_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "GRASS GROUND"
	next "FLYING BUG GAS"
	next "FUNGUS DRAGON"
	next ""
	next "WEAK AGAINST"
	next "FIRE ICE MAGMA"
	next "STEEL"
	done

_ManualType_ICE_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "FIRE FIGHTING ROCK"
	next "STEEL MAGMA"
	next ""
	next "RESISTS"
	next "ICE POISON FUNGUS"
	done

_ManualType_FAIRY_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "FIGHTING DRAGON"
	next "DARK"
	next ""
	next "WEAK AGAINST"
	next "FIRE POISON STEEL"
	done

_ManualType_FAIRY_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "FIRE POISON STEEL"
	next "MAGMA"
	next ""
	next "RESISTS"
	next "GRASS FIGHTING BUG"
	next "DRAGON DARK"
	done

_ManualType_GAS_ATK::
	text "AS AN ATTACKER"
	next "STRONG AGAINST"
	next "BUG GRASS"
	next ""
	next "WEAK AGAINST"
	next "ROCK GHOST FLYING"
	next "FIRE MAGMA STEEL"
	done

_ManualType_GAS_DEF::
	text "AS A DEFENDER"
	next "WEAK TO"
	next "FIRE ELECTRIC ICE"
	next "FLYING MAGMA"
	next ""
	next "RESISTS"
	next "NORMAL WATER BUG"
	next "ROCK STEEL"
	next ""
	next "IMMUNE TO"
	next "GROUND"
	done

