; v0.7: MOVE INFO flavour tables. Generated by .claude/flavor_build.py.
;
; Two parallel arrays indexed by move id - 1. The line count is stored rather
; than measured at runtime, so the card knows which row the mechanics start on
; without depending on where the first print happened to stop. A pointer of 0
; means no flavour is written for that move yet and the card prints the
; mechanics alone.

MoveFlavorPointers::
	table_width 2, MoveFlavorPointers
	dw MoveFlavor_CONSTRICT
	dw MoveFlavor_BUG_BITE
	dw MoveFlavor_LEECH_LIFE
	dw MoveFlavor_BUG_BUZZ
	dw MoveFlavor_MEGAHORN
	dw MoveFlavor_GUILLOTINE
	dw MoveFlavor_VICEGRIP
	dw MoveFlavor_TWINEEDLE
	dw MoveFlavor_FAINT_ATTACK
	dw MoveFlavor_RAGE
	dw MoveFlavor_NIGHT_SLASH
	dw MoveFlavor_BRUTAL_SWING
	dw MoveFlavor_DARK_PULSE
	dw MoveFlavor_GORE_ATTACK
	dw MoveFlavor_PAY_DAY
	dw MoveFlavor_DREAM_EATER
	dw MoveFlavor_DEEP_SLEEP
	dw MoveFlavor_DRAGON_RAGE
	dw MoveFlavor_DRAGON_CLAW
	dw MoveFlavor_DRAGON_BREATH
	dw MoveFlavor_DRAGON_SLAM
	dw MoveFlavor_OUTRAGE
	dw MoveFlavor_HYPER_BEAM
	dw MoveFlavor_NUZZLE
	dw MoveFlavor_THUNDERSHOCK
	dw MoveFlavor_SHOCK_WAVE
	dw MoveFlavor_THUNDERBOLT
	dw MoveFlavor_THUNDER
	dw MoveFlavor_THUNDER_WAVE
	dw MoveFlavor_VOLT_TACKLE
	dw MoveFlavor_DOUBLESLAP
	dw MoveFlavor_FAIRY_WIND
	dw MoveFlavor_DRAINING_KISS
	dw MoveFlavor_DAZZLE_GLEAM
	dw MoveFlavor_PLAY_ROUGH
	dw MoveFlavor_LOVELY_KISS
	dw MoveFlavor_SING
	dw MoveFlavor_MOONBLAST
	dw MoveFlavor_SEISMIC_TOSS
	dw MoveFlavor_LOW_KICK
	dw MoveFlavor_COMET_PUNCH
	dw MoveFlavor_BIND
	dw MoveFlavor_MACH_PUNCH
	dw MoveFlavor_KARATE_CHOP
	dw MoveFlavor_STRENGTH
	dw MoveFlavor_TAKE_DOWN
	dw MoveFlavor_LEEK_STRIKE
	dw MoveFlavor_DIZZY_PUNCH
	dw MoveFlavor_ROLLING_KICK
	dw MoveFlavor_SUBMISSION
	dw MoveFlavor_SKY_UPPERCUT
	dw MoveFlavor_HI_JUMP_KICK
	dw MoveFlavor_EMBER
	dw MoveFlavor_FLAME_CHARGE
	dw MoveFlavor_FLAME_BURST
	dw MoveFlavor_FLAMETHROWER
	dw MoveFlavor_FIRE_BLAST
	dw MoveFlavor_IGNITE
	dw MoveFlavor_EXPLOSION
	dw MoveFlavor_PECK
	dw MoveFlavor_GUST
	dw MoveFlavor_WING_ATTACK
	dw MoveFlavor_AERIAL_ACE
	dw MoveFlavor_FLY
	dw MoveFlavor_HURRICANE
	dw MoveFlavor_SKY_ATTACK
	dw MoveFlavor_DRILL_PECK
	dw MoveFlavor_SPORE_DAZE
	dw MoveFlavor_PARASITE
	dw MoveFlavor_SPORE
	dw MoveFlavor_SMOG
	dw MoveFlavor_HAZE
	dw MoveFlavor_POISON_GAS
	dw MoveFlavor_NIGHT_SHADE
	dw MoveFlavor_LICK
	dw MoveFlavor_ASTONISH
	dw MoveFlavor_SHADOW_SNEAK
	dw MoveFlavor_SHADOW_PUNCH
	dw MoveFlavor_SPIRIT_DRAIN
	dw MoveFlavor_SHADOW_BALL
	dw MoveFlavor_CONFUSE_RAY
	dw MoveFlavor_WILL_O_WISP
	dw MoveFlavor_ABSORB
	dw MoveFlavor_VINE_WHIP
	dw MoveFlavor_MEGA_DRAIN
	dw MoveFlavor_RAZOR_LEAF
	dw MoveFlavor_GIGA_DRAIN
	dw MoveFlavor_PETAL_DANCE
	dw MoveFlavor_SOLARBEAM
	dw MoveFlavor_LEECH_SEED
	dw MoveFlavor_POISONPOWDER
	dw MoveFlavor_STUN_POWDER
	dw MoveFlavor_SLEEP_POWDER
	dw MoveFlavor_GROUND_STOMP
	dw MoveFlavor_MUD_SHOT
	dw MoveFlavor_BULLDOZE
	dw MoveFlavor_MUD_BOMB
	dw MoveFlavor_EARTHQUAKE
	dw MoveFlavor_FISSURE
	dw MoveFlavor_BONE_CLUB
	dw MoveFlavor_DIG
	dw MoveFlavor_POWDER_SNOW
	dw MoveFlavor_ICY_WIND
	dw MoveFlavor_FROST_BREATH
	dw MoveFlavor_ICY_PULSE
	dw MoveFlavor_AURORA_BEAM
	dw MoveFlavor_ICE_BEAM
	dw MoveFlavor_BLIZZARD
	dw MoveFlavor_MAGMA_PUNCH
	dw MoveFlavor_LAVA_PLUME
	dw MoveFlavor_WRAP
	dw MoveFlavor_FURY_ATTACK
	dw MoveFlavor_SCRATCH
	dw MoveFlavor_TACKLE
	dw MoveFlavor_BITE
	dw MoveFlavor_QUICK_ATTACK
	dw MoveFlavor_HEADBUTT
	dw MoveFlavor_HORN_ATTACK
	dw MoveFlavor_SLASH
	dw MoveFlavor_BODY_SLAM
	dw MoveFlavor_CRUNCH
	dw MoveFlavor_HORN_CHARGE
	dw MoveFlavor_THRASH
	dw MoveFlavor_HEAVY_SLAM
	dw MoveFlavor_DOUBLE_EDGE
	dw MoveFlavor_EXTREMESPEED
	dw MoveFlavor_SUPERSONIC
	dw MoveFlavor_SUPER_FANG
	dw MoveFlavor_HYPER_FANG
	dw MoveFlavor_POISON_STING
	dw MoveFlavor_POISON_BITE
	dw MoveFlavor_TOXIC_FANGS
	dw MoveFlavor_ACID
	dw MoveFlavor_SLUDGE
	dw MoveFlavor_SLUDGE_WAVE
	dw MoveFlavor_GUNK_SHOT
	dw MoveFlavor_NEUROTOXIN
	dw MoveFlavor_TOXIC
	dw MoveFlavor_PSYWAVE
	dw MoveFlavor_CONFUSION
	dw MoveFlavor_EXTRASENSORY
	dw MoveFlavor_PSYBEAM
	dw MoveFlavor_PSYCHIC_M
	dw MoveFlavor_MIND_BREAK
	dw MoveFlavor_DISABLE
	dw MoveFlavor_HYPNOSIS
	dw MoveFlavor_ROCK_THROW
	dw MoveFlavor_ROCK_PUNCH
	dw MoveFlavor_ROCK_TOMB
	dw MoveFlavor_HEAD_SMASH
	dw MoveFlavor_ROCK_SLIDE
	dw MoveFlavor_CLAMP
	dw MoveFlavor_ROLLOUT
	dw MoveFlavor_BONEMERANG
	dw MoveFlavor_CRABHAMMER
	dw MoveFlavor_HORN_DRILL
	dw MoveFlavor_CUT
	dw MoveFlavor_IRON_TAIL
	dw MoveFlavor_IRON_HEAD
	dw MoveFlavor_SONICBOOM
	dw MoveFlavor_BULLET_PUNCH
	dw MoveFlavor_MAGNET_BOMB
	dw MoveFlavor_WATER_GUN
	dw MoveFlavor_AQUA_JET
	dw MoveFlavor_BUBBLEBEAM
	dw MoveFlavor_WATER_PULSE
	dw MoveFlavor_WATERFALL
	dw MoveFlavor_SURF
	dw MoveFlavor_HYDRO_PUMP
	dw MoveFlavor_TRI_ATTACK
	dw MoveFlavor_SWORDS_DANCE
	dw MoveFlavor_BULK_UP
	dw MoveFlavor_COIL
	dw MoveFlavor_FIERCE_ROAR
	dw MoveFlavor_HONE_CLAWS
	dw MoveFlavor_IRON_DEFENSE
	dw MoveFlavor_DEFENSE_CURL
	dw MoveFlavor_HARDEN
	dw MoveFlavor_WITHDRAW
	dw MoveFlavor_GROWTH
	dw MoveFlavor_CALM_MIND
	dw MoveFlavor_NASTY_PLOT
	dw MoveFlavor_AMNESIA
	dw MoveFlavor_QUIVER_DANCE
	dw MoveFlavor_TAILWIND
	dw MoveFlavor_AGILITY
	dw MoveFlavor_DOUBLE_TEAM
	dw MoveFlavor_TELEPORT
	dw MoveFlavor_CHARM
	dw MoveFlavor_INTIMIDATE
	dw MoveFlavor_GROWL
	dw MoveFlavor_LEER
	dw MoveFlavor_CORRODE
	dw MoveFlavor_TICKLE
	dw MoveFlavor_TAIL_WHIP
	dw MoveFlavor_FAKE_TEARS
	dw MoveFlavor_METAL_SOUND
	dw MoveFlavor_SCREECH
	dw MoveFlavor_EERIE_IMPULSE
	dw MoveFlavor_SCARY_FACE
	dw MoveFlavor_HINDER
	dw MoveFlavor_STRING_SHOT
	dw MoveFlavor_PSYCHIC_BIND
	dw MoveFlavor_FLASH
	dw MoveFlavor_SAND_ATTACK
	dw MoveFlavor_SMOKESCREEN
	dw MoveFlavor_RECOVER
	dw MoveFlavor_REST
	dw MoveFlavor_SOFTBOILED
	dw MoveFlavor_LIGHT_SCREEN
	dw MoveFlavor_REFLECT
	dw MoveFlavor_BIDE
	dw MoveFlavor_FOCUS_ENERGY
	dw MoveFlavor_MIMIC
	dw MoveFlavor_MIRROR_MOVE
	dw MoveFlavor_SUBSTITUTE
	dw MoveFlavor_TRANSFORM
	dw MoveFlavor_METRONOME
	dw MoveFlavor_STRUGGLE
	assert_table_length NUM_ATTACKS

MoveFlavorLines::
	table_width 1, MoveFlavorLines
	db 5
	db 4
	db 4
	db 4
	db 5
	db 4
	db 3
	db 4
	db 5
	db 4
	db 4
	db 5
	db 4
	db 5
	db 4
	db 4
	db 4
	db 4
	db 4
	db 4
	db 5
	db 4
	db 4
	db 5
	db 3
	db 4
	db 3
	db 3
	db 4
	db 4
	db 3
	db 4
	db 3
	db 3
	db 5
	db 6
	db 4
	db 4
	db 4
	db 4
	db 4
	db 5
	db 4
	db 3
	db 4
	db 4
	db 5
	db 4
	db 4
	db 4
	db 5
	db 4
	db 4
	db 4
	db 4
	db 4
	db 5
	db 3
	db 4
	db 3
	db 4
	db 4
	db 4
	db 4
	db 3
	db 4
	db 3
	db 4
	db 3
	db 4
	db 4
	db 4
	db 4
	db 4
	db 5
	db 4
	db 4
	db 4
	db 4
	db 3
	db 4
	db 4
	db 4
	db 5
	db 4
	db 3
	db 4
	db 4
	db 4
	db 4
	db 4
	db 4
	db 4
	db 4
	db 4
	db 4
	db 4
	db 4
	db 4
	db 4
	db 3
	db 4
	db 3
	db 4
	db 4
	db 3
	db 3
	db 4
	db 4
	db 4
	db 4
	db 4
	db 3
	db 4
	db 4
	db 4
	db 3
	db 4
	db 3
	db 4
	db 4
	db 4
	db 3
	db 4
	db 4
	db 4
	db 3
	db 4
	db 3
	db 3
	db 3
	db 3
	db 3
	db 4
	db 3
	db 5
	db 3
	db 3
	db 4
	db 4
	db 4
	db 4
	db 4
	db 5
	db 4
	db 4
	db 4
	db 4
	db 5
	db 4
	db 4
	db 3
	db 4
	db 4
	db 5
	db 4
	db 4
	db 4
	db 4
	db 4
	db 4
	db 4
	db 3
	db 3
	db 4
	db 4
	db 4
	db 3
	db 6
	db 4
	db 4
	db 4
	db 3
	db 4
	db 3
	db 4
	db 4
	db 3
	db 4
	db 5
	db 4
	db 5
	db 4
	db 4
	db 4
	db 4
	db 4
	db 4
	db 6
	db 4
	db 6
	db 4
	db 4
	db 4
	db 5
	db 5
	db 4
	db 3
	db 4
	db 5
	db 4
	db 4
	db 4
	db 4
	db 4
	db 3
	db 4
	db 4
	db 4
	db 4
	db 4
	db 4
	db 4
	db 3
	db 4
	db 4
	db 4
	db 4
	db 4
	assert_table_length NUM_ATTACKS

MoveFlavor_CONSTRICT:
	text_far _MoveFlavor_CONSTRICT
	text_end

MoveFlavor_BUG_BITE:
	text_far _MoveFlavor_BUG_BITE
	text_end

MoveFlavor_LEECH_LIFE:
	text_far _MoveFlavor_LEECH_LIFE
	text_end

MoveFlavor_BUG_BUZZ:
	text_far _MoveFlavor_BUG_BUZZ
	text_end

MoveFlavor_MEGAHORN:
	text_far _MoveFlavor_MEGAHORN
	text_end

MoveFlavor_GUILLOTINE:
	text_far _MoveFlavor_GUILLOTINE
	text_end

MoveFlavor_VICEGRIP:
	text_far _MoveFlavor_VICEGRIP
	text_end

MoveFlavor_TWINEEDLE:
	text_far _MoveFlavor_TWINEEDLE
	text_end

MoveFlavor_FAINT_ATTACK:
	text_far _MoveFlavor_FAINT_ATTACK
	text_end

MoveFlavor_RAGE:
	text_far _MoveFlavor_RAGE
	text_end

MoveFlavor_NIGHT_SLASH:
	text_far _MoveFlavor_NIGHT_SLASH
	text_end

MoveFlavor_BRUTAL_SWING:
	text_far _MoveFlavor_BRUTAL_SWING
	text_end

MoveFlavor_DARK_PULSE:
	text_far _MoveFlavor_DARK_PULSE
	text_end

MoveFlavor_GORE_ATTACK:
	text_far _MoveFlavor_GORE_ATTACK
	text_end

MoveFlavor_PAY_DAY:
	text_far _MoveFlavor_PAY_DAY
	text_end

MoveFlavor_DREAM_EATER:
	text_far _MoveFlavor_DREAM_EATER
	text_end

MoveFlavor_DEEP_SLEEP:
	text_far _MoveFlavor_DEEP_SLEEP
	text_end

MoveFlavor_DRAGON_RAGE:
	text_far _MoveFlavor_DRAGON_RAGE
	text_end

MoveFlavor_DRAGON_CLAW:
	text_far _MoveFlavor_DRAGON_CLAW
	text_end

MoveFlavor_DRAGON_BREATH:
	text_far _MoveFlavor_DRAGON_BREATH
	text_end

MoveFlavor_DRAGON_SLAM:
	text_far _MoveFlavor_DRAGON_SLAM
	text_end

MoveFlavor_OUTRAGE:
	text_far _MoveFlavor_OUTRAGE
	text_end

MoveFlavor_HYPER_BEAM:
	text_far _MoveFlavor_HYPER_BEAM
	text_end

MoveFlavor_NUZZLE:
	text_far _MoveFlavor_NUZZLE
	text_end

MoveFlavor_THUNDERSHOCK:
	text_far _MoveFlavor_THUNDERSHOCK
	text_end

MoveFlavor_SHOCK_WAVE:
	text_far _MoveFlavor_SHOCK_WAVE
	text_end

MoveFlavor_THUNDERBOLT:
	text_far _MoveFlavor_THUNDERBOLT
	text_end

MoveFlavor_THUNDER:
	text_far _MoveFlavor_THUNDER
	text_end

MoveFlavor_THUNDER_WAVE:
	text_far _MoveFlavor_THUNDER_WAVE
	text_end

MoveFlavor_VOLT_TACKLE:
	text_far _MoveFlavor_VOLT_TACKLE
	text_end

MoveFlavor_DOUBLESLAP:
	text_far _MoveFlavor_DOUBLESLAP
	text_end

MoveFlavor_FAIRY_WIND:
	text_far _MoveFlavor_FAIRY_WIND
	text_end

MoveFlavor_DRAINING_KISS:
	text_far _MoveFlavor_DRAINING_KISS
	text_end

MoveFlavor_DAZZLE_GLEAM:
	text_far _MoveFlavor_DAZZLE_GLEAM
	text_end

MoveFlavor_PLAY_ROUGH:
	text_far _MoveFlavor_PLAY_ROUGH
	text_end

MoveFlavor_LOVELY_KISS:
	text_far _MoveFlavor_LOVELY_KISS
	text_end

MoveFlavor_SING:
	text_far _MoveFlavor_SING
	text_end

MoveFlavor_MOONBLAST:
	text_far _MoveFlavor_MOONBLAST
	text_end

MoveFlavor_SEISMIC_TOSS:
	text_far _MoveFlavor_SEISMIC_TOSS
	text_end

MoveFlavor_LOW_KICK:
	text_far _MoveFlavor_LOW_KICK
	text_end

MoveFlavor_COMET_PUNCH:
	text_far _MoveFlavor_COMET_PUNCH
	text_end

MoveFlavor_BIND:
	text_far _MoveFlavor_BIND
	text_end

MoveFlavor_MACH_PUNCH:
	text_far _MoveFlavor_MACH_PUNCH
	text_end

MoveFlavor_KARATE_CHOP:
	text_far _MoveFlavor_KARATE_CHOP
	text_end

MoveFlavor_STRENGTH:
	text_far _MoveFlavor_STRENGTH
	text_end

MoveFlavor_TAKE_DOWN:
	text_far _MoveFlavor_TAKE_DOWN
	text_end

MoveFlavor_LEEK_STRIKE:
	text_far _MoveFlavor_LEEK_STRIKE
	text_end

MoveFlavor_DIZZY_PUNCH:
	text_far _MoveFlavor_DIZZY_PUNCH
	text_end

MoveFlavor_ROLLING_KICK:
	text_far _MoveFlavor_ROLLING_KICK
	text_end

MoveFlavor_SUBMISSION:
	text_far _MoveFlavor_SUBMISSION
	text_end

MoveFlavor_SKY_UPPERCUT:
	text_far _MoveFlavor_SKY_UPPERCUT
	text_end

MoveFlavor_HI_JUMP_KICK:
	text_far _MoveFlavor_HI_JUMP_KICK
	text_end

MoveFlavor_EMBER:
	text_far _MoveFlavor_EMBER
	text_end

MoveFlavor_FLAME_CHARGE:
	text_far _MoveFlavor_FLAME_CHARGE
	text_end

MoveFlavor_FLAME_BURST:
	text_far _MoveFlavor_FLAME_BURST
	text_end

MoveFlavor_FLAMETHROWER:
	text_far _MoveFlavor_FLAMETHROWER
	text_end

MoveFlavor_FIRE_BLAST:
	text_far _MoveFlavor_FIRE_BLAST
	text_end

MoveFlavor_IGNITE:
	text_far _MoveFlavor_IGNITE
	text_end

MoveFlavor_EXPLOSION:
	text_far _MoveFlavor_EXPLOSION
	text_end

MoveFlavor_PECK:
	text_far _MoveFlavor_PECK
	text_end

MoveFlavor_GUST:
	text_far _MoveFlavor_GUST
	text_end

MoveFlavor_WING_ATTACK:
	text_far _MoveFlavor_WING_ATTACK
	text_end

MoveFlavor_AERIAL_ACE:
	text_far _MoveFlavor_AERIAL_ACE
	text_end

MoveFlavor_FLY:
	text_far _MoveFlavor_FLY
	text_end

MoveFlavor_HURRICANE:
	text_far _MoveFlavor_HURRICANE
	text_end

MoveFlavor_SKY_ATTACK:
	text_far _MoveFlavor_SKY_ATTACK
	text_end

MoveFlavor_DRILL_PECK:
	text_far _MoveFlavor_DRILL_PECK
	text_end

MoveFlavor_SPORE_DAZE:
	text_far _MoveFlavor_SPORE_DAZE
	text_end

MoveFlavor_PARASITE:
	text_far _MoveFlavor_PARASITE
	text_end

MoveFlavor_SPORE:
	text_far _MoveFlavor_SPORE
	text_end

MoveFlavor_SMOG:
	text_far _MoveFlavor_SMOG
	text_end

MoveFlavor_HAZE:
	text_far _MoveFlavor_HAZE
	text_end

MoveFlavor_POISON_GAS:
	text_far _MoveFlavor_POISON_GAS
	text_end

MoveFlavor_NIGHT_SHADE:
	text_far _MoveFlavor_NIGHT_SHADE
	text_end

MoveFlavor_LICK:
	text_far _MoveFlavor_LICK
	text_end

MoveFlavor_ASTONISH:
	text_far _MoveFlavor_ASTONISH
	text_end

MoveFlavor_SHADOW_SNEAK:
	text_far _MoveFlavor_SHADOW_SNEAK
	text_end

MoveFlavor_SHADOW_PUNCH:
	text_far _MoveFlavor_SHADOW_PUNCH
	text_end

MoveFlavor_SPIRIT_DRAIN:
	text_far _MoveFlavor_SPIRIT_DRAIN
	text_end

MoveFlavor_SHADOW_BALL:
	text_far _MoveFlavor_SHADOW_BALL
	text_end

MoveFlavor_CONFUSE_RAY:
	text_far _MoveFlavor_CONFUSE_RAY
	text_end

MoveFlavor_WILL_O_WISP:
	text_far _MoveFlavor_WILL_O_WISP
	text_end

MoveFlavor_ABSORB:
	text_far _MoveFlavor_ABSORB
	text_end

MoveFlavor_VINE_WHIP:
	text_far _MoveFlavor_VINE_WHIP
	text_end

MoveFlavor_MEGA_DRAIN:
	text_far _MoveFlavor_MEGA_DRAIN
	text_end

MoveFlavor_RAZOR_LEAF:
	text_far _MoveFlavor_RAZOR_LEAF
	text_end

MoveFlavor_GIGA_DRAIN:
	text_far _MoveFlavor_GIGA_DRAIN
	text_end

MoveFlavor_PETAL_DANCE:
	text_far _MoveFlavor_PETAL_DANCE
	text_end

MoveFlavor_SOLARBEAM:
	text_far _MoveFlavor_SOLARBEAM
	text_end

MoveFlavor_LEECH_SEED:
	text_far _MoveFlavor_LEECH_SEED
	text_end

MoveFlavor_POISONPOWDER:
	text_far _MoveFlavor_POISONPOWDER
	text_end

MoveFlavor_STUN_POWDER:
	text_far _MoveFlavor_STUN_POWDER
	text_end

MoveFlavor_SLEEP_POWDER:
	text_far _MoveFlavor_SLEEP_POWDER
	text_end

MoveFlavor_GROUND_STOMP:
	text_far _MoveFlavor_GROUND_STOMP
	text_end

MoveFlavor_MUD_SHOT:
	text_far _MoveFlavor_MUD_SHOT
	text_end

MoveFlavor_BULLDOZE:
	text_far _MoveFlavor_BULLDOZE
	text_end

MoveFlavor_MUD_BOMB:
	text_far _MoveFlavor_MUD_BOMB
	text_end

MoveFlavor_EARTHQUAKE:
	text_far _MoveFlavor_EARTHQUAKE
	text_end

MoveFlavor_FISSURE:
	text_far _MoveFlavor_FISSURE
	text_end

MoveFlavor_BONE_CLUB:
	text_far _MoveFlavor_BONE_CLUB
	text_end

MoveFlavor_DIG:
	text_far _MoveFlavor_DIG
	text_end

MoveFlavor_POWDER_SNOW:
	text_far _MoveFlavor_POWDER_SNOW
	text_end

MoveFlavor_ICY_WIND:
	text_far _MoveFlavor_ICY_WIND
	text_end

MoveFlavor_FROST_BREATH:
	text_far _MoveFlavor_FROST_BREATH
	text_end

MoveFlavor_ICY_PULSE:
	text_far _MoveFlavor_ICY_PULSE
	text_end

MoveFlavor_AURORA_BEAM:
	text_far _MoveFlavor_AURORA_BEAM
	text_end

MoveFlavor_ICE_BEAM:
	text_far _MoveFlavor_ICE_BEAM
	text_end

MoveFlavor_BLIZZARD:
	text_far _MoveFlavor_BLIZZARD
	text_end

MoveFlavor_MAGMA_PUNCH:
	text_far _MoveFlavor_MAGMA_PUNCH
	text_end

MoveFlavor_LAVA_PLUME:
	text_far _MoveFlavor_LAVA_PLUME
	text_end

MoveFlavor_WRAP:
	text_far _MoveFlavor_WRAP
	text_end

MoveFlavor_FURY_ATTACK:
	text_far _MoveFlavor_FURY_ATTACK
	text_end

MoveFlavor_SCRATCH:
	text_far _MoveFlavor_SCRATCH
	text_end

MoveFlavor_TACKLE:
	text_far _MoveFlavor_TACKLE
	text_end

MoveFlavor_BITE:
	text_far _MoveFlavor_BITE
	text_end

MoveFlavor_QUICK_ATTACK:
	text_far _MoveFlavor_QUICK_ATTACK
	text_end

MoveFlavor_HEADBUTT:
	text_far _MoveFlavor_HEADBUTT
	text_end

MoveFlavor_HORN_ATTACK:
	text_far _MoveFlavor_HORN_ATTACK
	text_end

MoveFlavor_SLASH:
	text_far _MoveFlavor_SLASH
	text_end

MoveFlavor_BODY_SLAM:
	text_far _MoveFlavor_BODY_SLAM
	text_end

MoveFlavor_CRUNCH:
	text_far _MoveFlavor_CRUNCH
	text_end

MoveFlavor_HORN_CHARGE:
	text_far _MoveFlavor_HORN_CHARGE
	text_end

MoveFlavor_THRASH:
	text_far _MoveFlavor_THRASH
	text_end

MoveFlavor_HEAVY_SLAM:
	text_far _MoveFlavor_HEAVY_SLAM
	text_end

MoveFlavor_DOUBLE_EDGE:
	text_far _MoveFlavor_DOUBLE_EDGE
	text_end

MoveFlavor_EXTREMESPEED:
	text_far _MoveFlavor_EXTREMESPEED
	text_end

MoveFlavor_SUPERSONIC:
	text_far _MoveFlavor_SUPERSONIC
	text_end

MoveFlavor_SUPER_FANG:
	text_far _MoveFlavor_SUPER_FANG
	text_end

MoveFlavor_HYPER_FANG:
	text_far _MoveFlavor_HYPER_FANG
	text_end

MoveFlavor_POISON_STING:
	text_far _MoveFlavor_POISON_STING
	text_end

MoveFlavor_POISON_BITE:
	text_far _MoveFlavor_POISON_BITE
	text_end

MoveFlavor_TOXIC_FANGS:
	text_far _MoveFlavor_TOXIC_FANGS
	text_end

MoveFlavor_ACID:
	text_far _MoveFlavor_ACID
	text_end

MoveFlavor_SLUDGE:
	text_far _MoveFlavor_SLUDGE
	text_end

MoveFlavor_SLUDGE_WAVE:
	text_far _MoveFlavor_SLUDGE_WAVE
	text_end

MoveFlavor_GUNK_SHOT:
	text_far _MoveFlavor_GUNK_SHOT
	text_end

MoveFlavor_NEUROTOXIN:
	text_far _MoveFlavor_NEUROTOXIN
	text_end

MoveFlavor_TOXIC:
	text_far _MoveFlavor_TOXIC
	text_end

MoveFlavor_PSYWAVE:
	text_far _MoveFlavor_PSYWAVE
	text_end

MoveFlavor_CONFUSION:
	text_far _MoveFlavor_CONFUSION
	text_end

MoveFlavor_EXTRASENSORY:
	text_far _MoveFlavor_EXTRASENSORY
	text_end

MoveFlavor_PSYBEAM:
	text_far _MoveFlavor_PSYBEAM
	text_end

MoveFlavor_PSYCHIC_M:
	text_far _MoveFlavor_PSYCHIC_M
	text_end

MoveFlavor_MIND_BREAK:
	text_far _MoveFlavor_MIND_BREAK
	text_end

MoveFlavor_DISABLE:
	text_far _MoveFlavor_DISABLE
	text_end

MoveFlavor_HYPNOSIS:
	text_far _MoveFlavor_HYPNOSIS
	text_end

MoveFlavor_ROCK_THROW:
	text_far _MoveFlavor_ROCK_THROW
	text_end

MoveFlavor_ROCK_PUNCH:
	text_far _MoveFlavor_ROCK_PUNCH
	text_end

MoveFlavor_ROCK_TOMB:
	text_far _MoveFlavor_ROCK_TOMB
	text_end

MoveFlavor_HEAD_SMASH:
	text_far _MoveFlavor_HEAD_SMASH
	text_end

MoveFlavor_ROCK_SLIDE:
	text_far _MoveFlavor_ROCK_SLIDE
	text_end

MoveFlavor_CLAMP:
	text_far _MoveFlavor_CLAMP
	text_end

MoveFlavor_ROLLOUT:
	text_far _MoveFlavor_ROLLOUT
	text_end

MoveFlavor_BONEMERANG:
	text_far _MoveFlavor_BONEMERANG
	text_end

MoveFlavor_CRABHAMMER:
	text_far _MoveFlavor_CRABHAMMER
	text_end

MoveFlavor_HORN_DRILL:
	text_far _MoveFlavor_HORN_DRILL
	text_end

MoveFlavor_CUT:
	text_far _MoveFlavor_CUT
	text_end

MoveFlavor_IRON_TAIL:
	text_far _MoveFlavor_IRON_TAIL
	text_end

MoveFlavor_IRON_HEAD:
	text_far _MoveFlavor_IRON_HEAD
	text_end

MoveFlavor_SONICBOOM:
	text_far _MoveFlavor_SONICBOOM
	text_end

MoveFlavor_BULLET_PUNCH:
	text_far _MoveFlavor_BULLET_PUNCH
	text_end

MoveFlavor_MAGNET_BOMB:
	text_far _MoveFlavor_MAGNET_BOMB
	text_end

MoveFlavor_WATER_GUN:
	text_far _MoveFlavor_WATER_GUN
	text_end

MoveFlavor_AQUA_JET:
	text_far _MoveFlavor_AQUA_JET
	text_end

MoveFlavor_BUBBLEBEAM:
	text_far _MoveFlavor_BUBBLEBEAM
	text_end

MoveFlavor_WATER_PULSE:
	text_far _MoveFlavor_WATER_PULSE
	text_end

MoveFlavor_WATERFALL:
	text_far _MoveFlavor_WATERFALL
	text_end

MoveFlavor_SURF:
	text_far _MoveFlavor_SURF
	text_end

MoveFlavor_HYDRO_PUMP:
	text_far _MoveFlavor_HYDRO_PUMP
	text_end

MoveFlavor_TRI_ATTACK:
	text_far _MoveFlavor_TRI_ATTACK
	text_end

MoveFlavor_SWORDS_DANCE:
	text_far _MoveFlavor_SWORDS_DANCE
	text_end

MoveFlavor_BULK_UP:
	text_far _MoveFlavor_BULK_UP
	text_end

MoveFlavor_COIL:
	text_far _MoveFlavor_COIL
	text_end

MoveFlavor_FIERCE_ROAR:
	text_far _MoveFlavor_FIERCE_ROAR
	text_end

MoveFlavor_HONE_CLAWS:
	text_far _MoveFlavor_HONE_CLAWS
	text_end

MoveFlavor_IRON_DEFENSE:
	text_far _MoveFlavor_IRON_DEFENSE
	text_end

MoveFlavor_DEFENSE_CURL:
	text_far _MoveFlavor_DEFENSE_CURL
	text_end

MoveFlavor_HARDEN:
	text_far _MoveFlavor_HARDEN
	text_end

MoveFlavor_WITHDRAW:
	text_far _MoveFlavor_WITHDRAW
	text_end

MoveFlavor_GROWTH:
	text_far _MoveFlavor_GROWTH
	text_end

MoveFlavor_CALM_MIND:
	text_far _MoveFlavor_CALM_MIND
	text_end

MoveFlavor_NASTY_PLOT:
	text_far _MoveFlavor_NASTY_PLOT
	text_end

MoveFlavor_AMNESIA:
	text_far _MoveFlavor_AMNESIA
	text_end

MoveFlavor_QUIVER_DANCE:
	text_far _MoveFlavor_QUIVER_DANCE
	text_end

MoveFlavor_TAILWIND:
	text_far _MoveFlavor_TAILWIND
	text_end

MoveFlavor_AGILITY:
	text_far _MoveFlavor_AGILITY
	text_end

MoveFlavor_DOUBLE_TEAM:
	text_far _MoveFlavor_DOUBLE_TEAM
	text_end

MoveFlavor_TELEPORT:
	text_far _MoveFlavor_TELEPORT
	text_end

MoveFlavor_CHARM:
	text_far _MoveFlavor_CHARM
	text_end

MoveFlavor_INTIMIDATE:
	text_far _MoveFlavor_INTIMIDATE
	text_end

MoveFlavor_GROWL:
	text_far _MoveFlavor_GROWL
	text_end

MoveFlavor_LEER:
	text_far _MoveFlavor_LEER
	text_end

MoveFlavor_CORRODE:
	text_far _MoveFlavor_CORRODE
	text_end

MoveFlavor_TICKLE:
	text_far _MoveFlavor_TICKLE
	text_end

MoveFlavor_TAIL_WHIP:
	text_far _MoveFlavor_TAIL_WHIP
	text_end

MoveFlavor_FAKE_TEARS:
	text_far _MoveFlavor_FAKE_TEARS
	text_end

MoveFlavor_METAL_SOUND:
	text_far _MoveFlavor_METAL_SOUND
	text_end

MoveFlavor_SCREECH:
	text_far _MoveFlavor_SCREECH
	text_end

MoveFlavor_EERIE_IMPULSE:
	text_far _MoveFlavor_EERIE_IMPULSE
	text_end

MoveFlavor_SCARY_FACE:
	text_far _MoveFlavor_SCARY_FACE
	text_end

MoveFlavor_HINDER:
	text_far _MoveFlavor_HINDER
	text_end

MoveFlavor_STRING_SHOT:
	text_far _MoveFlavor_STRING_SHOT
	text_end

MoveFlavor_PSYCHIC_BIND:
	text_far _MoveFlavor_PSYCHIC_BIND
	text_end

MoveFlavor_FLASH:
	text_far _MoveFlavor_FLASH
	text_end

MoveFlavor_SAND_ATTACK:
	text_far _MoveFlavor_SAND_ATTACK
	text_end

MoveFlavor_SMOKESCREEN:
	text_far _MoveFlavor_SMOKESCREEN
	text_end

MoveFlavor_RECOVER:
	text_far _MoveFlavor_RECOVER
	text_end

MoveFlavor_REST:
	text_far _MoveFlavor_REST
	text_end

MoveFlavor_SOFTBOILED:
	text_far _MoveFlavor_SOFTBOILED
	text_end

MoveFlavor_LIGHT_SCREEN:
	text_far _MoveFlavor_LIGHT_SCREEN
	text_end

MoveFlavor_REFLECT:
	text_far _MoveFlavor_REFLECT
	text_end

MoveFlavor_BIDE:
	text_far _MoveFlavor_BIDE
	text_end

MoveFlavor_FOCUS_ENERGY:
	text_far _MoveFlavor_FOCUS_ENERGY
	text_end

MoveFlavor_MIMIC:
	text_far _MoveFlavor_MIMIC
	text_end

MoveFlavor_MIRROR_MOVE:
	text_far _MoveFlavor_MIRROR_MOVE
	text_end

MoveFlavor_SUBSTITUTE:
	text_far _MoveFlavor_SUBSTITUTE
	text_end

MoveFlavor_TRANSFORM:
	text_far _MoveFlavor_TRANSFORM
	text_end

MoveFlavor_METRONOME:
	text_far _MoveFlavor_METRONOME
	text_end

MoveFlavor_STRUGGLE:
	text_far _MoveFlavor_STRUGGLE
	text_end
