; GENERATED by .claude/manual_types_build.py from
; data/types/type_matchups.asm. Do not hand-edit: the point of
; generating it is that the TRAINER MANUAL cannot disagree with the
; table the battle engine reads. Re-run after changing a matchup.

TrainerManualTypeSections:
	db 21
	manual_section TrainerManualTypeNormalName, 0
	manual_section TrainerManualTypeFightingName, 2
	manual_section TrainerManualTypeFlyingName, 4
	manual_section TrainerManualTypePoisonName, 6
	manual_section TrainerManualTypeGroundName, 8
	manual_section TrainerManualTypeRockName, 10
	manual_section TrainerManualTypeBugName, 12
	manual_section TrainerManualTypeDragonName, 14
	manual_section TrainerManualTypeDarkName, 16
	manual_section TrainerManualTypeSteelName, 18
	manual_section TrainerManualTypeMagmaName, 20
	manual_section TrainerManualTypeFungusName, 22
	manual_section TrainerManualTypeGhostName, 24
	manual_section TrainerManualTypeFireName, 26
	manual_section TrainerManualTypeWaterName, 28
	manual_section TrainerManualTypeGrassName, 30
	manual_section TrainerManualTypeElectricName, 32
	manual_section TrainerManualTypePsychic_typeName, 34
	manual_section TrainerManualTypeIceName, 36
	manual_section TrainerManualTypeFairyName, 38
	manual_section TrainerManualTypeGasName, 40

TrainerManualTypePages:
	db 42
	dw ManualType_NORMAL_ATK
	dw ManualType_NORMAL_DEF
	dw ManualType_FIGHTING_ATK
	dw ManualType_FIGHTING_DEF
	dw ManualType_FLYING_ATK
	dw ManualType_FLYING_DEF
	dw ManualType_POISON_ATK
	dw ManualType_POISON_DEF
	dw ManualType_GROUND_ATK
	dw ManualType_GROUND_DEF
	dw ManualType_ROCK_ATK
	dw ManualType_ROCK_DEF
	dw ManualType_BUG_ATK
	dw ManualType_BUG_DEF
	dw ManualType_DRAGON_ATK
	dw ManualType_DRAGON_DEF
	dw ManualType_DARK_ATK
	dw ManualType_DARK_DEF
	dw ManualType_STEEL_ATK
	dw ManualType_STEEL_DEF
	dw ManualType_MAGMA_ATK
	dw ManualType_MAGMA_DEF
	dw ManualType_FUNGUS_ATK
	dw ManualType_FUNGUS_DEF
	dw ManualType_GHOST_ATK
	dw ManualType_GHOST_DEF
	dw ManualType_FIRE_ATK
	dw ManualType_FIRE_DEF
	dw ManualType_WATER_ATK
	dw ManualType_WATER_DEF
	dw ManualType_GRASS_ATK
	dw ManualType_GRASS_DEF
	dw ManualType_ELECTRIC_ATK
	dw ManualType_ELECTRIC_DEF
	dw ManualType_PSYCHIC_TYPE_ATK
	dw ManualType_PSYCHIC_TYPE_DEF
	dw ManualType_ICE_ATK
	dw ManualType_ICE_DEF
	dw ManualType_FAIRY_ATK
	dw ManualType_FAIRY_DEF
	dw ManualType_GAS_ATK
	dw ManualType_GAS_DEF

TrainerManualTypeNormalName:
	db "NORMAL@"
TrainerManualTypeFightingName:
	db "FIGHTING@"
TrainerManualTypeFlyingName:
	db "FLYING@"
TrainerManualTypePoisonName:
	db "POISON@"
TrainerManualTypeGroundName:
	db "GROUND@"
TrainerManualTypeRockName:
	db "ROCK@"
TrainerManualTypeBugName:
	db "BUG@"
TrainerManualTypeDragonName:
	db "DRAGON@"
TrainerManualTypeDarkName:
	db "DARK@"
TrainerManualTypeSteelName:
	db "STEEL@"
TrainerManualTypeMagmaName:
	db "MAGMA@"
TrainerManualTypeFungusName:
	db "FUNGUS@"
TrainerManualTypeGhostName:
	db "GHOST@"
TrainerManualTypeFireName:
	db "FIRE@"
TrainerManualTypeWaterName:
	db "WATER@"
TrainerManualTypeGrassName:
	db "GRASS@"
TrainerManualTypeElectricName:
	db "ELECTRIC@"
TrainerManualTypePsychic_typeName:
	db "PSYCHIC@"
TrainerManualTypeIceName:
	db "ICE@"
TrainerManualTypeFairyName:
	db "FAIRY@"
TrainerManualTypeGasName:
	db "GAS@"

	manual_page ManualType_NORMAL_ATK
	manual_page ManualType_NORMAL_DEF
	manual_page ManualType_FIGHTING_ATK
	manual_page ManualType_FIGHTING_DEF
	manual_page ManualType_FLYING_ATK
	manual_page ManualType_FLYING_DEF
	manual_page ManualType_POISON_ATK
	manual_page ManualType_POISON_DEF
	manual_page ManualType_GROUND_ATK
	manual_page ManualType_GROUND_DEF
	manual_page ManualType_ROCK_ATK
	manual_page ManualType_ROCK_DEF
	manual_page ManualType_BUG_ATK
	manual_page ManualType_BUG_DEF
	manual_page ManualType_DRAGON_ATK
	manual_page ManualType_DRAGON_DEF
	manual_page ManualType_DARK_ATK
	manual_page ManualType_DARK_DEF
	manual_page ManualType_STEEL_ATK
	manual_page ManualType_STEEL_DEF
	manual_page ManualType_MAGMA_ATK
	manual_page ManualType_MAGMA_DEF
	manual_page ManualType_FUNGUS_ATK
	manual_page ManualType_FUNGUS_DEF
	manual_page ManualType_GHOST_ATK
	manual_page ManualType_GHOST_DEF
	manual_page ManualType_FIRE_ATK
	manual_page ManualType_FIRE_DEF
	manual_page ManualType_WATER_ATK
	manual_page ManualType_WATER_DEF
	manual_page ManualType_GRASS_ATK
	manual_page ManualType_GRASS_DEF
	manual_page ManualType_ELECTRIC_ATK
	manual_page ManualType_ELECTRIC_DEF
	manual_page ManualType_PSYCHIC_TYPE_ATK
	manual_page ManualType_PSYCHIC_TYPE_DEF
	manual_page ManualType_ICE_ATK
	manual_page ManualType_ICE_DEF
	manual_page ManualType_FAIRY_ATK
	manual_page ManualType_FAIRY_DEF
	manual_page ManualType_GAS_ATK
	manual_page ManualType_GAS_DEF
