; GENERATED by .claude/manual_types_build.py from
; data/types/type_matchups.asm. Do not hand-edit: the point of
; generating it is that the TRAINER MANUAL cannot disagree with the
; table the battle engine reads. Re-run after changing a matchup.
;
; The rows below are FRAGMENTS: they are included in the middle of
; THE TYPES chapter's tables, after that chapter's own prose
; sections. MANUAL_TYPE_FIRST_PAGE is where those prose pages end,
; and is defined next to the tables that include this.

DEF MANUAL_NUM_TYPE_SECTIONS EQU 21
DEF MANUAL_NUM_TYPE_PAGES EQU 42

MACRO manual_type_sections
	manual_section TrainerManualTypeNormalName, MANUAL_TYPE_FIRST_PAGE + 0
	manual_section TrainerManualTypeFightingName, MANUAL_TYPE_FIRST_PAGE + 2
	manual_section TrainerManualTypeFlyingName, MANUAL_TYPE_FIRST_PAGE + 4
	manual_section TrainerManualTypePoisonName, MANUAL_TYPE_FIRST_PAGE + 6
	manual_section TrainerManualTypeGroundName, MANUAL_TYPE_FIRST_PAGE + 8
	manual_section TrainerManualTypeRockName, MANUAL_TYPE_FIRST_PAGE + 10
	manual_section TrainerManualTypeBugName, MANUAL_TYPE_FIRST_PAGE + 12
	manual_section TrainerManualTypeDragonName, MANUAL_TYPE_FIRST_PAGE + 14
	manual_section TrainerManualTypeDarkName, MANUAL_TYPE_FIRST_PAGE + 16
	manual_section TrainerManualTypeSteelName, MANUAL_TYPE_FIRST_PAGE + 18
	manual_section TrainerManualTypeMagmaName, MANUAL_TYPE_FIRST_PAGE + 20
	manual_section TrainerManualTypeFungusName, MANUAL_TYPE_FIRST_PAGE + 22
	manual_section TrainerManualTypeGhostName, MANUAL_TYPE_FIRST_PAGE + 24
	manual_section TrainerManualTypeFireName, MANUAL_TYPE_FIRST_PAGE + 26
	manual_section TrainerManualTypeWaterName, MANUAL_TYPE_FIRST_PAGE + 28
	manual_section TrainerManualTypeGrassName, MANUAL_TYPE_FIRST_PAGE + 30
	manual_section TrainerManualTypeElectricName, MANUAL_TYPE_FIRST_PAGE + 32
	manual_section TrainerManualTypePsychic_typeName, MANUAL_TYPE_FIRST_PAGE + 34
	manual_section TrainerManualTypeIceName, MANUAL_TYPE_FIRST_PAGE + 36
	manual_section TrainerManualTypeFairyName, MANUAL_TYPE_FIRST_PAGE + 38
	manual_section TrainerManualTypeGasName, MANUAL_TYPE_FIRST_PAGE + 40
ENDM

MACRO manual_type_pages
	dw ManualType_NORMAL_ATK
	dw ManualType_NORMAL_DEF
	dw ManualType_FIGHTING_ATK
	dw ManualType_FIGHTING_DEF
	dw ManualType_FLYING_ATK
	dw ManualType_FLYING_DEF
	dw ManualType_POISON_ATK
	dw ManualType_POISON_DEF
	dw ManualType_GROUND_ATK
	dw ManualType_GROUND_DEF
	dw ManualType_ROCK_ATK
	dw ManualType_ROCK_DEF
	dw ManualType_BUG_ATK
	dw ManualType_BUG_DEF
	dw ManualType_DRAGON_ATK
	dw ManualType_DRAGON_DEF
	dw ManualType_DARK_ATK
	dw ManualType_DARK_DEF
	dw ManualType_STEEL_ATK
	dw ManualType_STEEL_DEF
	dw ManualType_MAGMA_ATK
	dw ManualType_MAGMA_DEF
	dw ManualType_FUNGUS_ATK
	dw ManualType_FUNGUS_DEF
	dw ManualType_GHOST_ATK
	dw ManualType_GHOST_DEF
	dw ManualType_FIRE_ATK
	dw ManualType_FIRE_DEF
	dw ManualType_WATER_ATK
	dw ManualType_WATER_DEF
	dw ManualType_GRASS_ATK
	dw ManualType_GRASS_DEF
	dw ManualType_ELECTRIC_ATK
	dw ManualType_ELECTRIC_DEF
	dw ManualType_PSYCHIC_TYPE_ATK
	dw ManualType_PSYCHIC_TYPE_DEF
	dw ManualType_ICE_ATK
	dw ManualType_ICE_DEF
	dw ManualType_FAIRY_ATK
	dw ManualType_FAIRY_DEF
	dw ManualType_GAS_ATK
	dw ManualType_GAS_DEF
ENDM

TrainerManualTypeNormalName:
	db "NORMAL@"
TrainerManualTypeFightingName:
	db "FIGHTING@"
TrainerManualTypeFlyingName:
	db "FLYING@"
TrainerManualTypePoisonName:
	db "POISON@"
TrainerManualTypeGroundName:
	db "GROUND@"
TrainerManualTypeRockName:
	db "ROCK@"
TrainerManualTypeBugName:
	db "BUG@"
TrainerManualTypeDragonName:
	db "DRAGON@"
TrainerManualTypeDarkName:
	db "DARK@"
TrainerManualTypeSteelName:
	db "STEEL@"
TrainerManualTypeMagmaName:
	db "MAGMA@"
TrainerManualTypeFungusName:
	db "FUNGUS@"
TrainerManualTypeGhostName:
	db "GHOST@"
TrainerManualTypeFireName:
	db "FIRE@"
TrainerManualTypeWaterName:
	db "WATER@"
TrainerManualTypeGrassName:
	db "GRASS@"
TrainerManualTypeElectricName:
	db "ELECTRIC@"
TrainerManualTypePsychic_typeName:
	db "PSYCHIC@"
TrainerManualTypeIceName:
	db "ICE@"
TrainerManualTypeFairyName:
	db "FAIRY@"
TrainerManualTypeGasName:
	db "GAS@"

	manual_page ManualType_NORMAL_ATK
	manual_page ManualType_NORMAL_DEF
	manual_page ManualType_FIGHTING_ATK
	manual_page ManualType_FIGHTING_DEF
	manual_page ManualType_FLYING_ATK
	manual_page ManualType_FLYING_DEF
	manual_page ManualType_POISON_ATK
	manual_page ManualType_POISON_DEF
	manual_page ManualType_GROUND_ATK
	manual_page ManualType_GROUND_DEF
	manual_page ManualType_ROCK_ATK
	manual_page ManualType_ROCK_DEF
	manual_page ManualType_BUG_ATK
	manual_page ManualType_BUG_DEF
	manual_page ManualType_DRAGON_ATK
	manual_page ManualType_DRAGON_DEF
	manual_page ManualType_DARK_ATK
	manual_page ManualType_DARK_DEF
	manual_page ManualType_STEEL_ATK
	manual_page ManualType_STEEL_DEF
	manual_page ManualType_MAGMA_ATK
	manual_page ManualType_MAGMA_DEF
	manual_page ManualType_FUNGUS_ATK
	manual_page ManualType_FUNGUS_DEF
	manual_page ManualType_GHOST_ATK
	manual_page ManualType_GHOST_DEF
	manual_page ManualType_FIRE_ATK
	manual_page ManualType_FIRE_DEF
	manual_page ManualType_WATER_ATK
	manual_page ManualType_WATER_DEF
	manual_page ManualType_GRASS_ATK
	manual_page ManualType_GRASS_DEF
	manual_page ManualType_ELECTRIC_ATK
	manual_page ManualType_ELECTRIC_DEF
	manual_page ManualType_PSYCHIC_TYPE_ATK
	manual_page ManualType_PSYCHIC_TYPE_DEF
	manual_page ManualType_ICE_ATK
	manual_page ManualType_ICE_DEF
	manual_page ManualType_FAIRY_ATK
	manual_page ManualType_FAIRY_DEF
	manual_page ManualType_GAS_ATK
	manual_page ManualType_GAS_DEF
