CeruleanCave2F_Script:
	jp EnableAutoTextBoxDrawing

CeruleanCave2F_TextPointers:
	def_text_pointers
	dw_const PickUpItemText, TEXT_CERULEANCAVE2F_PP_MAX
	dw_const PickUpItemText, TEXT_CERULEANCAVE2F_MAX_REVIVE
	dw_const PickUpItemText, TEXT_CERULEANCAVE2F_FULL_RESTORE
